[project]
name = "nemdb"
version = "0.1.0"
description = "Utilities to process NEMWEB data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "click>=8.1.8",
    "fastexcel>=0.12.1",
    "fsspec>=2025.3.2",
    "gcsfs>=2025.3.2",
    "geopandas>=1.0.1",
    "numpy>=2.2.1",
    "openelectricity>=0.9.2",
    "pandas>=2.2.3",
    "pandera>=0.23.1",
    "polars>=1.29.0",
    "pre-commit>=4.2.0",
    "pytest-mock>=3.14.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "structlog>=25.1.0",
    "tqdm>=4.67.1",
]

[project.scripts]
populate = "nemdb:main.populate"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
    "pytest>=8.4.1",
    "ruff>=0.13.2",
]
doc = [
    "mkdocs>=1.6.1",
    "mkdocs-autoapi>=0.4.1",
    "mkdocs-material>=9.6.16",
    "mkdocstrings[python]>=0.30.1",
]
