[project]
name = "nemdb"
version = "0.1.0"
description = "Utilities to process NEMWEB data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "click>=8.1.8",
    "pandas>=2.2.3",
    "polars>=1.18.0",
    "pyarrow>=18.1.0",
    "pytest>=8.3.4",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "ruff>=0.8.4",
    "structlog>=24.4.0",
    "tqdm>=4.67.1",
]

[project.scripts]
populate = "nemdb:main.populate"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
