"""Pandera schemas for ISP 2025 tables.

Auto-generated by scripts/generate_isp2025_schemas.py — edit as needed.
"""

import pandera.polars as pa
import polars as pl
from pandera import Field


class ExistingGenerators(pa.DataFrameModel):
    iasr_id: pl.String
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    sub_region: pl.String = Field(nullable=True)
    rez_location: pl.String = Field(nullable=True)
    rez_id: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    regional_build_cost_zone: pl.String = Field(nullable=True)
    maximum_capacity_mw: pl.Float64 = Field(nullable=True)
    storage_capacity_mwh: pl.Float64 = Field(nullable=True)
    summer_peak_rating_mw: pl.String = Field(nullable=True)
    summer_typical_rating_mw: pl.Float64 = Field(nullable=True)
    winter_rating_mw: pl.Float64 = Field(nullable=True)
    minimum_stable_limit: pl.Float64 = Field(nullable=True)
    no_load_heat_rate: pl.Float64 = Field(nullable=True)
    marginal_heat_rate: pl.Float64 = Field(nullable=True)
    pumping_efficiency: pl.Float64 = Field(nullable=True)
    charge_efficiency: pl.Float64 = Field(nullable=True)
    discharge_efficiency: pl.Float64 = Field(nullable=True)
    allowable_max_state_of_charge: pl.Float64 = Field(nullable=True)
    allowable_min_state_of_charge: pl.Float64 = Field(nullable=True)
    round_trip_efficiency: pl.Float64 = Field(nullable=True)
    annual_degradation: pl.Float64 = Field(nullable=True)
    max_ramp_up_mw_min: pl.Float64 = Field(nullable=True)
    max_ramp_down_mw_min: pl.Float64 = Field(nullable=True)
    maintenance_proportion_of_time_out: pl.Float64 = Field(nullable=True)
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True
    )
    forced_outage_rate: pl.Float64 = Field(nullable=True)
    unnamed_30: pl.Float64 = Field(nullable=True)
    mean_time_to_repair_hrs: pl.Float64 = Field(nullable=True)
    unnamed_32: pl.Float64 = Field(nullable=True)
    derating_factor: pl.Float64 = Field(nullable=True)
    fom_kw_annum: pl.Float64 = Field(nullable=True)
    vom_mwh_sent_out: pl.Float64 = Field(nullable=True)
    heat_rate_gj_mwh_hhv_s_o: pl.Float64 = Field(nullable=True)
    fuel_cost_gj: pl.Float64 = Field(nullable=True)
    scope_1_emissions_kg_mwh: pl.Float64 = Field(nullable=True)
    mlf: pl.Float64 = Field(nullable=True)
    auxiliary_load_of_generation: pl.Float64 = Field(nullable=True)
    srmc_mwh: pl.Float64 = Field(nullable=True)
    expected_closure_year_calendar_year: pl.Float64 = Field(nullable=True)
    retirement_rehabilitation_cost_mw: pl.Float64 = Field(nullable=True)
    fault_level_replacement_cost_m: pl.Float64 = Field(nullable=True)


class NewEntrantGenerators(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    sub_region: pl.String = Field(nullable=True)
    rez_location: pl.String = Field(nullable=True)
    rez_id: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    regional_build_cost_zone: pl.String = Field(nullable=True)
    maximum_capacity_mw: pl.Float64 = Field(nullable=True)
    storage_capacity_hours: pl.Float64 = Field(nullable=True)
    seasonal_rating: pl.String = Field(nullable=True)
    unnamed_13: pl.String = Field(nullable=True)
    unnamed_14: pl.String = Field(nullable=True)
    min_stable_level_of_nameplate: pl.Float64 = Field(nullable=True)
    no_load_heat_rate: pl.Float64 = Field(nullable=True)
    marginal_heat_rate: pl.Float64 = Field(nullable=True)
    pumping_efficiency: pl.String = Field(nullable=True)
    charge_efficiency: pl.String = Field(nullable=True)
    discharge_efficiency: pl.String = Field(nullable=True)
    allowable_max_state_of_charge: pl.String = Field(nullable=True)
    allowable_min_state_of_charge: pl.String = Field(nullable=True)
    round_trip_efficiency: pl.String = Field(nullable=True)
    annual_degradation: pl.String = Field(nullable=True)
    max_ramp_up_mw_min: pl.String = Field(nullable=True)
    max_ramp_down_mw_min: pl.String = Field(nullable=True)
    maintenance_proportion_of_time_out: pl.Float64 = Field(nullable=True)
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True
    )
    forced_outage_rate: pl.String = Field(nullable=True)
    unnamed_30: pl.String = Field(nullable=True)
    mean_time_to_repair_hrs: pl.String = Field(nullable=True)
    unnamed_32: pl.String = Field(nullable=True)
    derating_factor: pl.String = Field(nullable=True)
    locational_cost_factors: pl.Float64 = Field(nullable=True)
    fom_kw_annum: pl.Float64 = Field(nullable=True)
    vom_mwh_sent_out: pl.Float64 = Field(nullable=True)
    heat_rate_gj_mwh_hhv_s_o: pl.Float64 = Field(nullable=True)
    fuel_cost_gj_1: pl.String = Field(nullable=True)
    scope_1_emissions_kg_mwh: pl.String = Field(nullable=True)
    mlf: pl.Float64 = Field(nullable=True)
    auxiliary_load_of_generation: pl.Float64 = Field(nullable=True)
    srmc_mwh: pl.Float64 = Field(nullable=True)
    expected_closure_year_calendar_year: pl.Date = Field(nullable=True)
    retirement_rehabilitation_cost_mw: pl.Float64 = Field(nullable=True)
    build_cost_kw: pl.String = Field(nullable=True)
    connection_cost_kw: pl.String = Field(nullable=True)
    efficient_level_of_system_strength_cost_kw: pl.String = Field(nullable=True)
    balance_of_plant_consumption: pl.String = Field(nullable=True)
    wacc: pl.String = Field(nullable=True)
    total_lead_time_years: pl.Float64 = Field(nullable=True)
    economic_life_years: pl.Float64 = Field(nullable=True)
    technical_life_years: pl.Float64 = Field(nullable=True)


class NewElectrolyserData(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    sub_region: pl.String = Field(nullable=True)
    rez_location: pl.String = Field(nullable=True)
    rez_id: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    regional_build_cost_zone: pl.String = Field(nullable=True)
    maximum_capacity_mw: pl.Float64 = Field(nullable=True)
    storage_capacity_hours: pl.Float64 = Field(nullable=True)
    seasonal_rating: pl.Float64 = Field(nullable=True)
    unnamed_13: pl.String = Field(nullable=True)
    unnamed_14: pl.String = Field(nullable=True)
    min_stable_level_of_nameplate: pl.Float64 = Field(nullable=True)
    maintenance_proportion_of_time_out: pl.Float64 = Field(nullable=True)
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True
    )
    forced_outage_rate: pl.String = Field(nullable=True)
    unnamed_19: pl.String = Field(nullable=True)
    mean_time_to_repair_hrs: pl.String = Field(nullable=True)
    unnamed_21: pl.String = Field(nullable=True)
    derating_factor: pl.String = Field(nullable=True)
    locational_cost_factors: pl.Float64 = Field(nullable=True)
    fom_kw_annum: pl.Float64 = Field(nullable=True)
    vom_mwh_sent_out: pl.Float64 = Field(nullable=True)
    heat_rate_gj_mwh_hhv_s_o: pl.Float64 = Field(nullable=True)
    scope_1_emissions_kg_mwh: pl.String = Field(nullable=True)
    mlf: pl.Float64 = Field(nullable=True)
    auxiliary_load_of_generation: pl.Float64 = Field(nullable=True)
    expected_closure_year_calendar_year: pl.Date = Field(nullable=True)
    retirement_rehabilitation_cost_mw: pl.Float64 = Field(nullable=True)
    build_cost_kw: pl.String = Field(nullable=True)
    associated_pipeline_cost_kw: pl.String = Field(nullable=True)
    connection_cost_kw: pl.String = Field(nullable=True)
    efficient_level_of_system_strength_cost_kw: pl.String = Field(nullable=True)
    balance_of_plant_consumption: pl.String = Field(nullable=True)
    wacc: pl.String = Field(nullable=True)
    total_lead_time_years: pl.Float64 = Field(nullable=True)
    economic_life_years: pl.Float64 = Field(nullable=True)
    technical_life_years: pl.Float64 = Field(nullable=True)
    minimum_capacity_utilization_factor: pl.String = Field(nullable=True)


class StorageProperties(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    maximum_power1: pl.Float64 = Field(nullable=True)
    energy_capacity2: pl.Float64 = Field(nullable=True)
    charge_efficiency: pl.Float64 = Field(nullable=True)
    discharge_efficiency: pl.Float64 = Field(nullable=True)
    allowable_max_state_of_charge: pl.Float64 = Field(nullable=True)
    allowable_min_state_of_charge: pl.Float64 = Field(nullable=True)
    round_trip_efficiency3: pl.Float64 = Field(nullable=True)
    annual_degradation4: pl.Float64 = Field(nullable=True)


class MaximumCapacity(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    status5: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    installed_capacity_mw: pl.Float64 = Field(nullable=True)
    storage_capacity_mwh: pl.Float64 = Field(nullable=True)
    commissioning_date: pl.Datetime = Field(nullable=True)
    policy: pl.String = Field(nullable=True)


class MaximumCapacityByTechnology(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    unit_size_mw: pl.Float64 = Field(nullable=True)
    number_of_units: pl.Float64 = Field(nullable=True)
    total_plant_size_mw: pl.Float64 = Field(nullable=True)


class SeasonalRatings(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    col_2024_25: pl.Float64 = Field(nullable=True)
    col_2025_26: pl.Float64 = Field(nullable=True)
    col_2026_27: pl.Float64 = Field(nullable=True)
    col_2027_28: pl.Float64 = Field(nullable=True)
    col_2028_29: pl.Float64 = Field(nullable=True)
    col_2029_30: pl.Float64 = Field(nullable=True)
    col_2030_31: pl.Float64 = Field(nullable=True)
    col_2031_32: pl.Float64 = Field(nullable=True)
    col_2032_33: pl.Float64 = Field(nullable=True)
    col_2033_34: pl.Float64 = Field(nullable=True)
    col_2024_25_1: pl.Float64 = Field(nullable=True)
    col_2025_26_1: pl.Float64 = Field(nullable=True)
    col_2026_27_1: pl.Float64 = Field(nullable=True)
    col_2027_28_1: pl.Float64 = Field(nullable=True)
    col_2028_29_1: pl.Float64 = Field(nullable=True)
    col_2029_30_1: pl.Float64 = Field(nullable=True)
    col_2030_31_1: pl.Float64 = Field(nullable=True)
    col_2031_32_1: pl.Float64 = Field(nullable=True)
    col_2032_33_1: pl.Float64 = Field(nullable=True)
    col_2033_34_1: pl.Float64 = Field(nullable=True)
    col_2024: pl.Float64 = Field(nullable=True)
    col_2025: pl.Float64 = Field(nullable=True)
    col_2026: pl.Float64 = Field(nullable=True)
    col_2027: pl.Float64 = Field(nullable=True)
    col_2028: pl.Float64 = Field(nullable=True)
    col_2029: pl.Float64 = Field(nullable=True)
    col_2030: pl.Float64 = Field(nullable=True)
    col_2031: pl.Float64 = Field(nullable=True)
    col_2032: pl.Float64 = Field(nullable=True)
    col_2033: pl.Float64 = Field(nullable=True)


class Maintenance(pa.DataFrameModel):
    generator_type: pl.String = Field(nullable=True)
    proportion_of_time_out: pl.Float64 = Field(nullable=True)
    equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(nullable=True)


class MaintenanceByTechnology(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    proportion_of_time_out: pl.Float64 = Field(nullable=True)
    equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(nullable=True)


class GeneratorReliability(pa.DataFrameModel):
    fuel_type: pl.String = Field(nullable=True)
    property: pl.String = Field(nullable=True)
    col_2025_26: pl.Float64 = Field(nullable=True)
    col_2026_27: pl.Float64 = Field(nullable=True)
    col_2027_28: pl.Float64 = Field(nullable=True)
    col_2028_29: pl.Float64 = Field(nullable=True)
    col_2029_30: pl.Float64 = Field(nullable=True)
    col_2030_31: pl.Float64 = Field(nullable=True)
    col_2031_32: pl.Float64 = Field(nullable=True)
    col_2032_33: pl.Float64 = Field(nullable=True)
    col_2033_34: pl.Float64 = Field(nullable=True)
    col_2034_35: pl.Float64 = Field(nullable=True)


class Retirement(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    expected_closure_year_calendar_year: pl.Date = Field(nullable=True)
    col5: pl.String = Field(nullable=True)


class RetirementCosts(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    retirement_mw: pl.Float64 = Field(nullable=True)


class HeatRates(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    heat_rate_gj_mwh: pl.Float64 = Field(nullable=True)


class HeatRatesByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    heat_rate_gj_mwh: pl.Float64 = Field(nullable=True)


class Auxiliary(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    auxiliary_load_of_generation: pl.Float64 = Field(nullable=True)


class AuxiliaryByTechnology(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    auxiliary_load_of_generation: pl.Float64 = Field(nullable=True)


class EmissionsIntensity(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    scope_1_emissions_intensity_kg_mwh_as_gen: pl.Float64 = Field(nullable=True)


class EmissionsIntensityByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    scope_1_emissions_intensity_kg_mwh_as_gen: pl.Float64 = Field(nullable=True)


class FixedOpex(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    fixed_opex_kw_year: pl.Float64 = Field(nullable=True)


class FixedOpexByTechnology(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    base_value_kw_year: pl.Float64 = Field(nullable=True)
    unit: pl.String = Field(nullable=True)


class VariableOpex(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station_technology: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    variable_opex_mwh_sent_out_1: pl.Float64 = Field(nullable=True)


class VariableOpexByTechnology(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    base_value: pl.Float64 = Field(nullable=True)


class AffineHeatRates(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    no_load_heat_input_gj_h: pl.Float64 = Field(nullable=True)
    marginal_heat_rate_gj_mwh: pl.Float64 = Field(nullable=True)


class AffineHeatRatesByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    unit_nominal_capacity_mw: pl.Float64 = Field(nullable=True)
    no_load_heat_input_gj_h: pl.Float64 = Field(nullable=True)
    marginal_heat_rate_gj_mwh: pl.Float64 = Field(nullable=True)


class MaxRampRates(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    max_ramp_up_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_down_mw_min: pl.Float64 = Field(nullable=True, coerce=True)


class MaxRampRatesByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    max_ramp_up_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_down_mw_min: pl.Float64 = Field(nullable=True, coerce=True)


class CoalMinStableLevel(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    iasr_2023_backcasting: pl.String = Field(nullable=True)
    typical_lowest_band: pl.Float64 = Field(nullable=True)
    minimum_continuous_operating_level: pl.Float64 = Field(nullable=True)


class GpgMinStableLevel(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    min_stable_level_mw: pl.Float64 = Field(nullable=True)


class GpgMinStableLevelByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    min_stable_level_of_nameplate: pl.Float64 = Field(nullable=True)


class LeadTimeProjectLife(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    lead_time_for_development_years_1_2: pl.Float64 = Field(nullable=True)
    lead_time_years_3: pl.Float64 = Field(nullable=True)
    construction_time_years: pl.Float64 = Field(nullable=True)
    total_lead_time_years_4_7: pl.Float64 = Field(nullable=True)
    economic_life_years_5: pl.Float64 = Field(nullable=True)
    technical_life_years_6: pl.Float64 = Field(nullable=True)


class FinancialParameters(pa.DataFrameModel):
    parameter: pl.String = Field(nullable=True)
    note: pl.String = Field(nullable=True)
    lower_bound: pl.String = Field(nullable=True)
    central: pl.String = Field(nullable=True)
    upper_bound: pl.String = Field(nullable=True)


class GasSystemProperties(pa.DataFrameModel):
    name: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    location: pl.String = Field(nullable=True)
    capacity_tj_per_day: pl.String = Field(nullable=True)
    source: pl.String = Field(nullable=True)


class RenewableEnergyZones(pa.DataFrameModel):
    id: pl.String = Field(nullable=True)
    name: pl.String = Field(nullable=True)
    nem_region: pl.String = Field(nullable=True)
    isp_sub_region: pl.String = Field(nullable=True)


class NetworkCapability(pa.DataFrameModel):
    flow_paths: pl.String = Field(nullable=True)
    forward_peak_demand_mw: pl.String = Field(nullable=True)
    forward_summer_typical_mw: pl.String = Field(nullable=True)
    forward_winter_reference_mw: pl.String = Field(nullable=True)
    reverse_peak_demand_mw: pl.String = Field(nullable=True)
    reverse_summer_typical_mw: pl.String = Field(nullable=True)
    reverse_winter_reference_mw: pl.String = Field(nullable=True)
    dominant_constraints_forward: pl.String = Field(nullable=True)
    dominant_constraints_reverse: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)
    flow_path_type: pl.String = Field(nullable=True)


class NetworkLosses(pa.DataFrameModel):
    flow_path: pl.String = Field(nullable=True)
    interconnector_flow_path_name: pl.String = Field(nullable=True)
    from_region_sub_region: pl.String = Field(nullable=True)
    to_region_subregion: pl.String = Field(nullable=True)
    loss_equation: pl.String = Field(nullable=True)
    mlf_equation: pl.String = Field(nullable=True)
    from_region_loss_proportion: pl.String = Field(nullable=True)
    to_region_loss_proportion: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class TransmissionReliability(pa.DataFrameModel):
    line_flowpath: pl.String = Field(nullable=True)
    implementation: pl.String = Field(nullable=True)
    unplanned_outage_rate: pl.Float64 = Field(nullable=True)
    mean_time_to_repair: pl.Float64 = Field(nullable=True)


class ConnectionCost(pa.DataFrameModel):
    rez_id: pl.String = Field(nullable=True)
    rez_names: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    rez_network_voltage_kv: pl.String = Field(nullable=True)
    connection_capacity_mva: pl.String = Field(nullable=True)
    feeder_length_km: pl.String = Field(nullable=True)
    total_cost_m: pl.String = Field(nullable=True)
    kw: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class FlowPathAugmentation(pa.DataFrameModel):
    flow_path: pl.String = Field(nullable=True)
    development_path: pl.String = Field(nullable=True)
    development_driver: pl.String = Field(nullable=True)
    option_name: pl.String = Field(nullable=True)
    augmentation_description: pl.String = Field(nullable=True)
    pre_requisite_options: pl.String = Field(nullable=True)
    forward_direction_power_flow: pl.String = Field(nullable=True)
    notional_transfer_level_increase_forward_mw: pl.String = Field(nullable=True)
    notional_transfer_level_increase_reverse_mw: pl.String = Field(nullable=True)
    indicative_cost_estimate_2025_million: pl.String = Field(nullable=True)
    cost_estimate_source: pl.String = Field(nullable=True)
    cost_estimate_class: pl.String = Field(nullable=True)
    easement_length_km: pl.String = Field(nullable=True)
    lead_time_or_earliest_in_service_date: pl.String = Field(nullable=True)
    additional_rez_transmission_capacity_provided: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class RezAugmentations(pa.DataFrameModel):
    rez_constraint_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    option: pl.String = Field(nullable=True)
    augmentation_description: pl.String = Field(nullable=True)
    pre_requisite_options: pl.String = Field(nullable=True)
    additional_network_capacity_mw: pl.String = Field(nullable=True)
    additional_import_capacity_mw: pl.String = Field(nullable=True)
    expected_cost_2025_million: pl.String = Field(nullable=True)
    cost_estimate_source: pl.String = Field(nullable=True)
    cost_estimate_class: pl.String = Field(nullable=True)
    m_mw: pl.String = Field(nullable=True)
    easement_length_km: pl.String = Field(nullable=True)
    lead_time: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class BuildLimitsRez(pa.DataFrameModel):
    rez_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    wind_generation_total_limits_mw: pl.String = Field(nullable=True)
    unnamed_3: pl.String = Field(nullable=True)
    unnamed_4: pl.String = Field(nullable=True)
    unnamed_5: pl.String = Field(nullable=True)
    solar_pv_plus_solar_thermal_limits_mw: pl.String = Field(nullable=True)
    rez_resource_limit_violation_penalty_factor_m_mw: pl.String = Field(nullable=True)
    land_use_limits_in_mw: pl.String = Field(nullable=True)
    unnamed_9: pl.String = Field(nullable=True)
    land_use_limits_in_mw_accelerated_transition_scenario: pl.String = Field(nullable=True)
    unnamed_11: pl.String = Field(nullable=True)
    land_area_km2_additional_table_note_1: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class BuildLimitsPhes(pa.DataFrameModel):
    name: pl.String = Field(nullable=True)
    isp_sub_region: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    pumped_hydro_energy_storage_phes_limits_mw: pl.String = Field(nullable=True)


class LocationalCostFactors(pa.DataFrameModel):
    cost_zone_rez_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    equipment_and_installation_costs: pl.String = Field(nullable=True)
    fuel_connection_costs: pl.String = Field(nullable=True)
    cost_of_land_and_development_2: pl.String = Field(nullable=True)
    installation_costs: pl.String = Field(nullable=True)
    o_m_costs_3: pl.String = Field(nullable=True)


class CapacityFactors(pa.DataFrameModel):
    rez_id_subregion: pl.String = Field(nullable=True)
    rez_name_subregion_name: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    col_2010_11: pl.Float64 = Field(nullable=True)
    col_2011_12: pl.Float64 = Field(nullable=True)
    col_2012_13: pl.Float64 = Field(nullable=True)
    col_2013_14: pl.Float64 = Field(nullable=True)
    col_2014_15: pl.Float64 = Field(nullable=True)
    col_2015_16: pl.Float64 = Field(nullable=True)
    col_2016_17: pl.Float64 = Field(nullable=True)
    col_2017_18: pl.Float64 = Field(nullable=True)
    col_2018_19: pl.Float64 = Field(nullable=True)
    col_2019_20: pl.Float64 = Field(nullable=True)
    col_2020_21: pl.Float64 = Field(nullable=True)
    col_2021_22: pl.Float64 = Field(nullable=True)
    col_2022_23: pl.Float64 = Field(nullable=True)
    col_2023_24: pl.Float64 = Field(nullable=True)
    col_2024_25: pl.Float64 = Field(nullable=True)
    avg_of_reference_years: pl.Float64 = Field(nullable=True)
    comment: pl.String = Field(nullable=True)


class MarginalLossFactors(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    tni_code: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    mlf: pl.String = Field(nullable=True)
    shadow_connection_point: pl.String = Field(nullable=True)
    generator_group: pl.String = Field(nullable=True)


class HydroSchemeInflows(pa.DataFrameModel):
    reference_year_fye: pl.String = Field(nullable=True)
    jul: pl.String = Field(nullable=True)
    aug: pl.String = Field(nullable=True)
    sep: pl.String = Field(nullable=True)
    oct: pl.String = Field(nullable=True)
    nov: pl.String = Field(nullable=True)
    dec: pl.String = Field(nullable=True)
    jan: pl.String = Field(nullable=True)
    feb: pl.String = Field(nullable=True)
    mar: pl.String = Field(nullable=True)
    apr: pl.String = Field(nullable=True)
    may: pl.String = Field(nullable=True)
    jun: pl.String = Field(nullable=True)
    annual_total: pl.String = Field(nullable=True)


class BuildCosts(pa.DataFrameModel):
    technology1: pl.String = Field(nullable=True)
    gencost_scenario: pl.String = Field(nullable=True)
    iasr_scenario: pl.String = Field(nullable=True)
    source: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class ConnectionCostForecasts(pa.DataFrameModel):
    rez_id: pl.String = Field(nullable=True)
    rez_names: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class ConnectionCostOtherGeneration(pa.DataFrameModel):
    generator_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    cost_aud_kw: pl.Float64 = Field(nullable=True)


class FlowPathCostForecasts(pa.DataFrameModel):
    flow_path: pl.String = Field(nullable=True)
    option: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class RezCostForecasts(pa.DataFrameModel):
    rez_constraint_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    option: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class DistributionCostForecasts(pa.DataFrameModel):
    distributon_network_service_provider: pl.String = Field(nullable=True)
    distribution_network_upgrade_tranche: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class CoalBiomassPrice(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)


class GasLiquidH2Price(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    gas_price_scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)
    price_category: pl.String = Field(nullable=True)


class RooftopPv(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class Pvnsg(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class Onsg(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class BatteryPluginEvs(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    subregion: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class FuelCellEvs(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    subregion: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class EvV2g(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class Dsp(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    price_band: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    season: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class DataCentreForecasts(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class Electrification(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class EmbeddedEnergyStorages(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class AggregatedEnergyStorages(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class EndUseFuelConsumption(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    fuel_sector: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class ApplianceUptake(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class ElecRetailPriceIndices(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class ConnectionsForecasts(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class EnergyEfficiency(pa.DataFrameModel):
    section: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class HydrogenDemandDomestic(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class HydrogenDemandExport(pa.DataFrameModel):
    isp_subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class HydrogenMonthlyProfiles(pa.DataFrameModel):
    month: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class WaterForHydrogen(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class DesalinationDemandH2(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class H2GpgLimit(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class BuildCostHydrogenPipeline(pa.DataFrameModel):
    electrolyser_pipeline: pl.String = Field(nullable=True)
    demand_location: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    rez: pl.String = Field(nullable=True)
    length_km: pl.Float64 = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class GpgEmissionsReduction(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class FuelPriceSummary(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    rez_sub_region: pl.String = Field(nullable=True)
    fuel_cost_mapping: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    price_gj: pl.Float64 = Field(nullable=True)
    generator_status: pl.String = Field(nullable=True)


class EconomicGrowthForecasts(pa.DataFrameModel):
    metric: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True)


class PowerSystemSecurity(pa.DataFrameModel):
    duid: pl.String = Field(nullable=True)
    generator_name: pl.String = Field(nullable=True)
    fault_level_replacement_cost_m: pl.String = Field(nullable=True)
