"""Pandera schemas for ISP 2025 tables.

Auto-generated by scripts/generate_isp2025_schemas.py — edit as needed.
"""

import pandera.polars as pa
import polars as pl
from pandera import Field


class ExistingGenerators(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    sub_region: pl.String = Field(nullable=True)
    rez_location: pl.String = Field(nullable=True)
    rez_id: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    regional_build_cost_zone: pl.String = Field(nullable=True, coerce=True)
    maximum_capacity_mw: pl.Float64 = Field(nullable=True, coerce=True)
    storage_capacity_mwh: pl.Float64 = Field(nullable=True, coerce=True)
    summer_peak_rating_mw_2025_26: pl.Float64 = Field(nullable=True, coerce=True)
    summer_typical_rating_mw_2025_26: pl.Float64 = Field(nullable=True, coerce=True)
    winter_rating_mw_2025: pl.Float64 = Field(nullable=True, coerce=True)
    minimum_stable_limit: pl.Float64 = Field(nullable=True, coerce=True)
    no_load_heat_rate: pl.Float64 = Field(nullable=True, coerce=True)
    marginal_heat_rate: pl.Float64 = Field(nullable=True, coerce=True)
    pumping_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    charge_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    discharge_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    allowable_max_state_of_charge_pct: pl.Float64 = Field(nullable=True, coerce=True)
    allowable_min_state_of_charge_pct: pl.Float64 = Field(nullable=True, coerce=True)
    round_trip_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    annual_degradation_pct: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_up_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_down_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    maintenance_proportion_of_time_out_pct: pl.Float64 = Field(nullable=True, coerce=True)
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    forced_outage_rate_pct_full_outage_pct_of_time_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    forced_outage_rate_pct_partial_outage_pct_of_time_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    mean_time_to_repair_hrs_full_outage_mttr_hrs_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    mean_time_to_repair_hrs_partial_outage_mttr_hrs_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    derating_factor_pct_partial_outage_derating_factor_pct_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    fom_aud_kw_annum: pl.Float64 = Field(nullable=True, coerce=True)
    vom_aud_mwh_sent_out: pl.Float64 = Field(nullable=True, coerce=True)
    heat_rate_gj_mwh_hhv_so: pl.Float64 = Field(nullable=True, coerce=True)
    fuel_cost_aud_gj_slower_growth_2025_26: pl.Float64 = Field(nullable=True, coerce=True)
    scope_1_emissions_kg_mwh_accelerated_transition_2038_39: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    mlf: pl.Float64 = Field(nullable=True, coerce=True)
    auxiliary_load_pct_of_generation: pl.Float64 = Field(nullable=True, coerce=True)
    srmc_aud_mwh: pl.Float64 = Field(nullable=True, coerce=True)
    expected_closure_year_calendar_year: pl.Float64 = Field(nullable=True, coerce=True)
    retirement_rehabilitation_cost_aud_mw: pl.Float64 = Field(nullable=True, coerce=True)
    fault_level_replacement_cost_audm: pl.Float64 = Field(nullable=True, coerce=True)


class NewEntrantGenerators(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    sub_region: pl.String = Field(nullable=True)
    rez_location: pl.String = Field(nullable=True)
    rez_id: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    regional_build_cost_zone: pl.String = Field(nullable=True)
    maximum_capacity_mw: pl.Float64 = Field(nullable=True, coerce=True)
    storage_capacity_hours: pl.Float64 = Field(nullable=True, coerce=True)
    seasonal_rating_summer_peak_rating_pct_of_nameplate: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    seasonal_rating_summer_typical_rating_pct_of_nameplate: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    seasonal_rating_winter_rating_pct_of_nameplate: pl.Float64 = Field(nullable=True, coerce=True)
    min_stable_level_pct_of_nameplate: pl.Float64 = Field(nullable=True, coerce=True)
    no_load_heat_rate: pl.Float64 = Field(nullable=True, coerce=True)
    marginal_heat_rate: pl.Float64 = Field(nullable=True, coerce=True)
    pumping_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    charge_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    discharge_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    allowable_max_state_of_charge_pct: pl.Float64 = Field(nullable=True, coerce=True)
    allowable_min_state_of_charge_pct: pl.Float64 = Field(nullable=True, coerce=True)
    round_trip_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)
    annual_degradation_pct: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_up_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_down_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    maintenance_proportion_of_time_out_pct: pl.Float64 = Field(nullable=True, coerce=True)
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    forced_outage_rate_pct_full_outage_pct_of_time_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    forced_outage_rate_pct_partial_outage_pct_of_time_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    mean_time_to_repair_hrs_full_outage_mttr_hrs_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    mean_time_to_repair_hrs_partial_outage_mttr_hrs_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    derating_factor_pct_partial_outage_derating_factor_pct_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    locational_cost_factors: pl.Float64 = Field(nullable=True, coerce=True)
    fom_aud_kw_annum: pl.Float64 = Field(nullable=True, coerce=True)
    vom_aud_mwh_sent_out: pl.Float64 = Field(nullable=True, coerce=True)
    heat_rate_gj_mwh_hhv_so: pl.Float64 = Field(nullable=True, coerce=True)
    fuel_cost_aud_gj1_slower_growth_2025_26: pl.Float64 = Field(nullable=True, coerce=True)
    scope_1_emissions_kg_mwh_step_change_2051_52: pl.Float64 = Field(nullable=True, coerce=True)
    mlf: pl.Float64 = Field(nullable=True, coerce=True)
    auxiliary_load_pct_of_generation: pl.Float64 = Field(nullable=True, coerce=True)
    srmc_aud_mwh: pl.Float64 = Field(nullable=True, coerce=True)
    expected_closure_year_calendar_year: pl.Float64 = Field(nullable=True, coerce=True)
    retirement_rehabilitation_cost_aud_mw: pl.Float64 = Field(nullable=True, coerce=True)
    build_cost_aud_kw_step_change_2027_28: pl.Float64 = Field(nullable=True, coerce=True)
    connection_cost_aud_kw_step_change_2027_28: pl.Float64 = Field(nullable=True, coerce=True)
    efficient_level_of_system_strength_cost_aud_kw_2025_26: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    balance_of_plant_consumption_pct_step_change: pl.Float64 = Field(nullable=True, coerce=True)
    wacc_pct_step_change: pl.Float64 = Field(nullable=True, coerce=True)
    total_lead_time_years: pl.Float64 = Field(nullable=True, coerce=True)
    economic_life_years: pl.Float64 = Field(nullable=True, coerce=True)
    technical_life_years: pl.Float64 = Field(nullable=True, coerce=True)


class NewElectrolyserData(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    sub_region: pl.String = Field(nullable=True)
    rez_location: pl.String = Field(nullable=True)
    rez_id: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    regional_build_cost_zone: pl.String = Field(nullable=True)
    maximum_capacity_mw: pl.Float64 = Field(nullable=True, coerce=True)
    storage_capacity_hours: pl.Float64 = Field(nullable=True, coerce=True)
    seasonal_rating: pl.Float64 = Field(nullable=True, coerce=True)
    col13: pl.Float64 = Field(nullable=True, coerce=True)
    col14: pl.Float64 = Field(nullable=True, coerce=True)
    min_stable_level_pct_of_nameplate: pl.Float64 = Field(nullable=True, coerce=True)
    maintenance_proportion_of_time_out_pct: pl.Float64 = Field(nullable=True, coerce=True)
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    forced_outage_rate_pct: pl.Float64 = Field(nullable=True, coerce=True)
    col19: pl.Float64 = Field(nullable=True, coerce=True)
    mean_time_to_repair_hrs: pl.Float64 = Field(nullable=True, coerce=True)
    col21: pl.Float64 = Field(nullable=True, coerce=True)
    derating_factor_pct: pl.Float64 = Field(nullable=True, coerce=True)
    locational_cost_factors: pl.Float64 = Field(nullable=True, coerce=True)
    fom_aud_kw_annum: pl.Float64 = Field(nullable=True, coerce=True)
    vom_aud_mwh_sent_out: pl.Float64 = Field(nullable=True, coerce=True)
    heat_rate_gj_mwh_hhv_so: pl.Float64 = Field(nullable=True, coerce=True)
    scope_1_emissions_kg_mwh: pl.Float64 = Field(nullable=True, coerce=True)
    mlf: pl.Float64 = Field(nullable=True, coerce=True)
    auxiliary_load_pct_of_generation: pl.Float64 = Field(nullable=True, coerce=True)
    expected_closure_year_calendar_year: pl.Float64 = Field(nullable=True, coerce=True)
    retirement_rehabilitation_cost_aud_mw: pl.Float64 = Field(nullable=True, coerce=True)
    build_cost_aud_kw: pl.Float64 = Field(nullable=True, coerce=True)
    associated_pipeline_cost_aud_kw: pl.Float64 = Field(nullable=True, coerce=True)
    connection_cost_aud_kw: pl.Float64 = Field(nullable=True, coerce=True)
    efficient_level_of_system_strength_cost_aud_kw: pl.Float64 = Field(nullable=True, coerce=True)
    balance_of_plant_consumption_pct: pl.Float64 = Field(nullable=True, coerce=True)
    wacc_pct: pl.Float64 = Field(nullable=True, coerce=True)
    total_lead_time_years: pl.Float64 = Field(nullable=True, coerce=True)
    economic_life_years: pl.Float64 = Field(nullable=True, coerce=True)
    technical_life_years: pl.Float64 = Field(nullable=True, coerce=True)
    minimum_capacity_utilization_factor_pct: pl.Float64 = Field(nullable=True, coerce=True)


class StorageBatteryProperties(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    maximum_power: pl.Float64 = Field(nullable=True, coerce=True)
    energy_capacity: pl.Float64 = Field(nullable=True, coerce=True)
    charge_efficiency: pl.Float64 = Field(nullable=True, coerce=True)
    discharge_efficiency: pl.Float64 = Field(nullable=True, coerce=True)
    allowable_max_state_of_charge: pl.Float64 = Field(nullable=True, coerce=True)
    allowable_min_state_of_charge: pl.Float64 = Field(nullable=True, coerce=True)
    round_trip_efficiency: pl.Float64 = Field(nullable=True, coerce=True)
    annual_degradation: pl.Float64 = Field(nullable=True, coerce=True)


class StorageHydroProperties(pa.DataFrameModel):
    type: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    installed_capacity_mw: pl.Float64 = Field(nullable=True, coerce=True)
    storage_capacity_hours: pl.Float64 = Field(nullable=True, coerce=True)
    pumping_efficiency_pct: pl.Float64 = Field(nullable=True, coerce=True)


class MaximumCapacity(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    installed_capacity_mw: pl.Float64 = Field(nullable=True, coerce=True)
    storage_capacity_mwh: pl.Float64 = Field(nullable=True, coerce=True)
    commissioning_date: pl.Date = Field(nullable=True)
    policy: pl.String = Field(nullable=True)


class MaximumCapacityByTechnology(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    unit_size_mw: pl.Float64 = Field(nullable=True, coerce=True)
    number_of_units: pl.Float64 = Field(nullable=True, coerce=True)
    total_plant_size_mw: pl.Float64 = Field(nullable=True, coerce=True)


class SeasonalRatings(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    generator_group: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    summer_peak_pct_of_nameplate: pl.Float64 = Field(nullable=True, coerce=True)
    summer_typical_pct_of_nameplate: pl.Float64 = Field(nullable=True, coerce=True)
    winter_pct_of_nameplate: pl.Float64 = Field(nullable=True, coerce=True)


class Maintenance(pa.DataFrameModel):
    generator_type: pl.String = Field(nullable=True)
    proportion_of_time_out_pct: pl.Float64 = Field(nullable=True, coerce=True)
    equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True, coerce=True
    )


class MaintenanceByTechnology(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    proportion_of_time_out_pct: pl.Float64 = Field(nullable=True, coerce=True)
    equivalent_average_days_per_year_on_planned_outage: pl.Float64 = Field(
        nullable=True, coerce=True
    )


class GeneratorReliability(pa.DataFrameModel):
    fuel_type: pl.String = Field(nullable=True)
    property: pl.String = Field(nullable=True)


class Retirement(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    expected_closure_year_calendar_year: pl.String = Field(nullable=True)


class RetirementCosts(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    retirement_mw: pl.Float64 = Field(nullable=True, coerce=True)


class HeatRates(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    heat_rate_gj_mwh: pl.Float64 = Field(nullable=True, coerce=True)


class HeatRatesByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    heat_rate_gj_mwh: pl.Float64 = Field(nullable=True, coerce=True)


class Auxiliary(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    auxiliary_load_pct_of_generation: pl.Float64 = Field(nullable=True, coerce=True)


class AuxiliaryByTechnology(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    auxiliary_load_pct_of_generation: pl.Float64 = Field(nullable=True, coerce=True)


class EmissionsIntensity(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    scope_1_emissions_intensity_kg_mwh_as_gen: pl.Float64 = Field(nullable=True, coerce=True)


class EmissionsIntensityByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    scope_1_emissions_intensity_kg_mwh_as_gen: pl.Float64 = Field(nullable=True, coerce=True)


class FixedOpex(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    fixed_opex_aud_kw_year: pl.Float64 = Field(nullable=True, coerce=True)


class FixedOpexByTechnology(pa.DataFrameModel):
    technology_type: pl.String = Field(nullable=True)
    base_value_kw_year: pl.Float64 = Field(nullable=True, coerce=True)
    unit: pl.String = Field(nullable=True)


class VariableOpex(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station_technology: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    variable_opex_aud_mwh_sent_out: pl.Float64 = Field(nullable=True, coerce=True)


class VariableOpexByTechnology(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    base_value: pl.Float64 = Field(nullable=True, coerce=True)


class AffineHeatRates(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    no_load_heat_input_gj_h: pl.Float64 = Field(nullable=True, coerce=True)
    marginal_heat_rate_gj_mwh: pl.Float64 = Field(nullable=True, coerce=True)


class AffineHeatRatesByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    unit_nominal_capacity_mw: pl.Float64 = Field(nullable=True, coerce=True)
    no_load_heat_input_gj_h: pl.Float64 = Field(nullable=True, coerce=True)
    marginal_heat_rate_gj_mwh: pl.Float64 = Field(nullable=True, coerce=True)


class MaxRampRates(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    max_ramp_up_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_down_mw_min: pl.Float64 = Field(nullable=True, coerce=True)


class MaxRampRatesByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    max_ramp_up_mw_min: pl.Float64 = Field(nullable=True, coerce=True)
    max_ramp_down_mw_min: pl.Float64 = Field(nullable=True, coerce=True)


class CoalMinStableLevel(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    iasr_2023_backcasting: pl.Float64 = Field(nullable=True, coerce=True)
    typical_lowest_band: pl.Float64 = Field(nullable=True, coerce=True)
    minimum_continuous_operating_level: pl.Float64 = Field(nullable=True, coerce=True)


class GpgMinStableLevel(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    technology_type: pl.String = Field(nullable=True)
    min_stable_level_mw: pl.Float64 = Field(nullable=True, coerce=True)


class GpgMinStableLevelByTechnology(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    min_stable_level_of_nameplate: pl.Float64 = Field(nullable=True, coerce=True)


class LeadTimeProjectLife(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    lead_time_for_development_years: pl.Float64 = Field(nullable=True, coerce=True)
    lead_time_years: pl.Float64 = Field(nullable=True, coerce=True)
    construction_time_years: pl.Float64 = Field(nullable=True, coerce=True)
    total_lead_time_years: pl.Float64 = Field(nullable=True, coerce=True)
    economic_life_years: pl.Float64 = Field(nullable=True, coerce=True)
    technical_life_years: pl.Float64 = Field(nullable=True, coerce=True)


class FinancialParameters(pa.DataFrameModel):
    parameter: pl.String = Field(nullable=True)
    note: pl.String = Field(nullable=True)
    lower_bound: pl.String = Field(nullable=True)
    central: pl.String = Field(nullable=True)
    upper_bound: pl.String = Field(nullable=True)


class GasSystemProperties(pa.DataFrameModel):
    name: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    location: pl.String = Field(nullable=True)
    capacity_tj_per_day: pl.String = Field(nullable=True)
    source: pl.String = Field(nullable=True)


class RenewableEnergyZones(pa.DataFrameModel):
    id: pl.String = Field(nullable=True)
    name: pl.String = Field(nullable=True)
    nem_region: pl.String = Field(nullable=True)
    isp_sub_region: pl.String = Field(nullable=True)


class NetworkCapability(pa.DataFrameModel):
    flow_paths: pl.String = Field(nullable=True)
    forward_peak_demand_mw: pl.String = Field(nullable=True)
    forward_summer_typical_mw: pl.String = Field(nullable=True)
    forward_winter_reference_mw: pl.String = Field(nullable=True)
    reverse_peak_demand_mw: pl.String = Field(nullable=True)
    reverse_summer_typical_mw: pl.String = Field(nullable=True)
    reverse_winter_reference_mw: pl.String = Field(nullable=True)
    dominant_constraints_forward: pl.String = Field(nullable=True)
    dominant_constraints_reverse: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)
    flow_path_type: pl.String = Field(nullable=True)


class NetworkLosses(pa.DataFrameModel):
    flow_path: pl.String = Field(nullable=True)
    interconnector_flow_path_name: pl.String = Field(nullable=True)
    from_region_sub_region: pl.String = Field(nullable=True)
    to_region_subregion: pl.String = Field(nullable=True)
    loss_equation: pl.String = Field(nullable=True)
    mlf_equation: pl.String = Field(nullable=True)
    from_region_loss_proportion: pl.String = Field(nullable=True)
    to_region_loss_proportion: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class TransmissionReliability(pa.DataFrameModel):
    line_flowpath: pl.String = Field(nullable=True)
    implementation: pl.String = Field(nullable=True)
    unplanned_outage_rate_pct: pl.Float64 = Field(nullable=True, coerce=True)
    mean_time_to_repair: pl.Float64 = Field(nullable=True, coerce=True)


class ConnectionCost(pa.DataFrameModel):
    rez_id: pl.String = Field(nullable=True)
    rez_names: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    rez_network_voltage_kv: pl.String = Field(nullable=True)
    connection_capacity_mva: pl.String = Field(nullable=True)
    feeder_length_km: pl.String = Field(nullable=True)
    total_cost_audm: pl.String = Field(nullable=True)
    aud_kw: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class FlowPathAugmentation(pa.DataFrameModel):
    flow_path: pl.String = Field(nullable=True)
    development_path: pl.String = Field(nullable=True)
    development_driver: pl.String = Field(nullable=True)
    option_name: pl.String = Field(nullable=True)
    augmentation_description: pl.String = Field(nullable=True)
    pre_requisite_options: pl.String = Field(nullable=True)
    forward_direction_power_flow: pl.String = Field(nullable=True)
    notional_transfer_level_increase_forward_mw: pl.String = Field(nullable=True)
    notional_transfer_level_increase_reverse_mw: pl.String = Field(nullable=True)
    indicative_cost_estimate_2025_million: pl.String = Field(nullable=True)
    cost_estimate_source: pl.String = Field(nullable=True)
    cost_estimate_class: pl.String = Field(nullable=True)
    easement_length_km: pl.String = Field(nullable=True)
    lead_time_or_earliest_in_service_date: pl.String = Field(nullable=True)
    additional_rez_transmission_capacity_provided: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class RezAugmentations(pa.DataFrameModel):
    rez_constraint_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    option: pl.String = Field(nullable=True)
    augmentation_description: pl.String = Field(nullable=True)
    pre_requisite_options: pl.String = Field(nullable=True)
    additional_network_capacity_mw: pl.String = Field(nullable=True)
    additional_import_capacity_mw: pl.String = Field(nullable=True)
    expected_cost_aud2025_million: pl.String = Field(nullable=True)
    cost_estimate_source: pl.String = Field(nullable=True)
    cost_estimate_class: pl.String = Field(nullable=True)
    audm_mw: pl.String = Field(nullable=True)
    easement_length_km: pl.String = Field(nullable=True)
    lead_time: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)


class BuildLimitsRez(pa.DataFrameModel):
    """Initial resource limits by REZ (wind, solar, land use)."""

    rez_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    wind_generation_total_limits_mw_high: pl.Float64 = Field(nullable=True, coerce=True)
    wind_generation_total_limits_mw_medium: pl.Float64 = Field(nullable=True, coerce=True)
    wind_generation_total_limits_mw_offshore_fixed: pl.Float64 = Field(nullable=True, coerce=True)
    wind_generation_total_limits_mw_offshore_floating: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    solar_pv_plus_solar_thermal_limits_mw_solar: pl.Float64 = Field(nullable=True, coerce=True)
    rez_resource_limit_violation_penalty_factor_audm_mw: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    land_use_limits_in_mw_wind: pl.Float64 = Field(nullable=True, coerce=True)
    land_use_limits_in_mw_solar: pl.Float64 = Field(nullable=True, coerce=True)
    land_use_limits_in_mw_accelerated_transition_scenario_wind: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    land_use_limits_in_mw_accelerated_transition_scenario_solar: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    land_area_km2_additional_table_note_1: pl.Float64 = Field(nullable=True, coerce=True)
    notes: pl.String = Field(nullable=True)


class BuildLimitsRezTransmission(pa.DataFrameModel):
    """Initial transmission limits by REZ (network limits, expansion costs)."""

    rez_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    additional_constraint_information: pl.String = Field(nullable=True)
    rez_transmission_network_limit_peak_demand: pl.Float64 = Field(nullable=True, coerce=True)
    rez_transmission_network_limit_summer_typical: pl.Float64 = Field(nullable=True, coerce=True)
    rez_transmission_network_limit_winter_reference: pl.Float64 = Field(nullable=True, coerce=True)
    electrolyser_import_limit: pl.String = Field(nullable=True)
    indicative_transmission_expansion_cost_audm_mw_tranche_1: pl.String = Field(nullable=True)
    indicative_transmission_expansion_cost_audm_mw_tranche_2: pl.String = Field(nullable=True)
    indicative_transmission_expansion_cost_audm_mw_tranche_2_conditions: pl.String = Field(
        nullable=True
    )
    indicative_transmission_expansion_cost_audm_mw_tranche_3: pl.String = Field(nullable=True)
    indicative_transmission_expansion_cost_audm_mw_tranche_3_conditions: pl.String = Field(
        nullable=True
    )
    notes: pl.String = Field(nullable=True)


class BuildLimitsRezModifiers(pa.DataFrameModel):
    """REZ transmission limit modifiers due to committed/anticipated augmentations."""

    rez_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    augmentation_name: pl.String = Field(nullable=True)
    rez_transmission_limit_increase_mw: pl.Float64 = Field(nullable=True, coerce=True)
    notes: pl.String = Field(nullable=True)


class RezGroupConstraints(pa.DataFrameModel):
    """REZ group/transmission constraint with build limits and expansion costs.

    Shared by group constraints summary, transmission limit constraints,
    and secondary transmission limit tables.
    """

    term: pl.String = Field(nullable=True)
    description: pl.String = Field(nullable=True)
    group_constraint_id: pl.String = Field(nullable=True)
    transmission_limited_total_build_summer_peak: pl.Float64 = Field(nullable=True, coerce=True)
    transmission_limited_total_build_summer_typical: pl.Float64 = Field(nullable=True, coerce=True)
    transmission_limited_total_build_winter_reference: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    indicative_transmission_expansion_cost_audm_mw: pl.Float64 = Field(nullable=True, coerce=True)
    indicative_transmission_expansion_cost_audm_mw_tranche_2: pl.Float64 = Field(
        nullable=True, coerce=True
    )
    notes: pl.String = Field(nullable=True)


class BuildLimitsPhes(pa.DataFrameModel):
    name: pl.String = Field(nullable=True)
    isp_sub_region: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    pumped_hydro_energy_storage_phes_limits_mw: pl.String = Field(nullable=True)


class LocationalCostFactors(pa.DataFrameModel):
    cost_zone_rez_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    equipment_and_installation_costs: pl.String = Field(nullable=True)
    fuel_connection_costs: pl.String = Field(nullable=True)
    cost_of_land_and_development_2: pl.String = Field(nullable=True)
    installation_costs: pl.String = Field(nullable=True)
    om_costs: pl.String = Field(nullable=True)


class LocationalCostFactorsPhes(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    duration: pl.String = Field(nullable=True)
    equipment_and_installation_costs: pl.Float64 = Field(nullable=True, coerce=True)
    fuel_connection_costs: pl.Float64 = Field(nullable=True, coerce=True)
    cost_of_land_and_development: pl.Float64 = Field(nullable=True, coerce=True)
    installation_costs: pl.Float64 = Field(nullable=True, coerce=True)
    topographical_cost: pl.Float64 = Field(nullable=True, coerce=True)
    om_costs: pl.Float64 = Field(nullable=True, coerce=True)


class LocationalCostFactorsTechnologySpecific(pa.DataFrameModel):
    cost_zone_rez_id: pl.String = Field(nullable=True)
    rez_name_description: pl.String = Field(nullable=True)
    ocgt_small_gt: pl.Float64 = Field(nullable=True, coerce=True)
    ocgt_large_gt: pl.Float64 = Field(nullable=True, coerce=True)
    ccgt: pl.Float64 = Field(nullable=True, coerce=True)
    ccgt_with_ccs: pl.Float64 = Field(nullable=True, coerce=True)
    biomass: pl.Float64 = Field(nullable=True, coerce=True)
    large_scale_solar_pv: pl.Float64 = Field(nullable=True, coerce=True)
    solar_thermal_16hrs_storage: pl.Float64 = Field(nullable=True, coerce=True)
    battery_storage_1hr_storage: pl.Float64 = Field(nullable=True, coerce=True)
    battery_storage_2hrs_storage: pl.Float64 = Field(nullable=True, coerce=True)
    battery_storage_4hrs_storage: pl.Float64 = Field(nullable=True, coerce=True)
    battery_storage_8hrs_storage: pl.Float64 = Field(nullable=True, coerce=True)
    wind: pl.Float64 = Field(nullable=True, coerce=True)
    wind_offshore_fixed: pl.Float64 = Field(nullable=True, coerce=True)
    wind_offshore_floating: pl.Float64 = Field(nullable=True, coerce=True)
    pumped_hydro_10hrs_storage: pl.Float64 = Field(nullable=True, coerce=True)
    pumped_hydro_24hrs_storage: pl.Float64 = Field(nullable=True, coerce=True)
    pumped_hydro_48hrs_storage: pl.Float64 = Field(nullable=True, coerce=True)
    distributed_resources_solar: pl.Float64 = Field(nullable=True, coerce=True)
    distributed_resources_batteries: pl.Float64 = Field(nullable=True, coerce=True)
    alkaline_electrolyser: pl.Float64 = Field(nullable=True, coerce=True)
    botn_cethana: pl.Float64 = Field(nullable=True, coerce=True)


class CapacityFactors(pa.DataFrameModel):
    rez_id_subregion: pl.String = Field(nullable=True)
    rez_name_subregion_name: pl.String = Field(nullable=True)
    technology: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    avg_of_reference_years: pl.Float64 = Field(nullable=True, coerce=True)
    comment: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class MarginalLossFactors(pa.DataFrameModel):
    iasr_id: pl.String = Field(nullable=True)
    tni_code: pl.String = Field(nullable=True)
    power_station: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    mlf: pl.Float64 = Field(nullable=True, coerce=True)
    shadow_connection_point: pl.String = Field(nullable=True)
    generator_group: pl.String = Field(nullable=True)


class HydroSchemeInflows(pa.DataFrameModel):
    reference_year_fye: pl.String = Field(nullable=True)
    jul: pl.Float64 = Field(nullable=True, coerce=True)
    aug: pl.Float64 = Field(nullable=True, coerce=True)
    sep: pl.Float64 = Field(nullable=True, coerce=True)
    oct: pl.Float64 = Field(nullable=True, coerce=True)
    nov: pl.Float64 = Field(nullable=True, coerce=True)
    dec: pl.Float64 = Field(nullable=True, coerce=True)
    jan: pl.Float64 = Field(nullable=True, coerce=True)
    feb: pl.Float64 = Field(nullable=True, coerce=True)
    mar: pl.Float64 = Field(nullable=True, coerce=True)
    apr: pl.Float64 = Field(nullable=True, coerce=True)
    may: pl.Float64 = Field(nullable=True, coerce=True)
    jun: pl.Float64 = Field(nullable=True, coerce=True)
    annual_total: pl.Float64 = Field(nullable=True, coerce=True)


class BuildCosts(pa.DataFrameModel):
    technology: pl.String = Field(nullable=True)
    gencost_scenario: pl.String = Field(nullable=True)
    iasr_scenario: pl.String = Field(nullable=True)
    source: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class ConnectionCostForecastsWindSolar(pa.DataFrameModel):
    rez_id: pl.String = Field(nullable=True)
    rez_names: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)
    cost_type: pl.String = Field(nullable=True)


class ConnectionCostForecastsOther(pa.DataFrameModel):
    generator_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)
    cost_type: pl.String = Field(nullable=True)


class ConnectionCostOtherGeneration(pa.DataFrameModel):
    generator_type: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    cost_aud_kw: pl.Float64 = Field(nullable=True, coerce=True)


class FlowPathCostForecasts(pa.DataFrameModel):
    flow_path: pl.String = Field(nullable=True)
    option: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class RezCostForecasts(pa.DataFrameModel):
    rez_constraint_id: pl.String = Field(nullable=True)
    rez_name: pl.String = Field(nullable=True)
    option: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class DistributionCostForecasts(pa.DataFrameModel):
    distributon_network_service_provider: pl.String = Field(nullable=True)
    distribution_network_upgrade_tranche: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    notes: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class CoalBiomassPrice(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)
    fuel_type: pl.String = Field(nullable=True)


class GasLiquidH2Price(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    price_scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)
    price_category: pl.String = Field(nullable=True)


class RooftopPv(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class Pvnsg(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class Onsg(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class BatteryPluginEvs(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    subregion: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class FuelCellEvs(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    subregion: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class EvV2g(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class Dsp(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    price_band: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    season: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class DataCentreForecasts(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class Electrification(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class EmbeddedEnergyStorages(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class AggregatedEnergyStorages(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class EndUseFuelConsumption(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    fuel_sector: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class ApplianceUptake(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class ElecRetailPriceIndices(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class ConnectionsForecasts(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class EnergyEfficiency(pa.DataFrameModel):
    section: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class HydrogenDemandDomestic(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class HydrogenDemandExport(pa.DataFrameModel):
    isp_subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class HydrogenMonthlyProfiles(pa.DataFrameModel):
    month: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class WaterForHydrogen(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class DesalinationDemandH2(pa.DataFrameModel):
    subregion: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class H2GpgLimit(pa.DataFrameModel):
    region: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class BuildCostHydrogenPipeline(pa.DataFrameModel):
    electrolyser_pipeline: pl.String = Field(nullable=True)
    demand_location: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    rez: pl.String = Field(nullable=True)
    length_km: pl.Float64 = Field(nullable=True, coerce=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class GpgEmissionsReduction(pa.DataFrameModel):
    scenario: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class FuelPriceSummary(pa.DataFrameModel):
    generator: pl.String = Field(nullable=True)
    status: pl.String = Field(nullable=True)
    region: pl.String = Field(nullable=True)
    fuel_type: pl.String = Field(nullable=True)
    rez_sub_region: pl.String = Field(nullable=True)
    fuel_cost_mapping: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    price_gj: pl.Float64 = Field(nullable=True, coerce=True)
    generator_status: pl.String = Field(nullable=True)


class EconomicGrowthForecasts(pa.DataFrameModel):
    metric: pl.String = Field(nullable=True)
    scenario: pl.String = Field(nullable=True)
    state: pl.String = Field(nullable=True)
    year: pl.Date = Field(nullable=True)
    value: pl.Float64 = Field(nullable=True, coerce=True)


class PowerSystemSecurity(pa.DataFrameModel):
    duid: pl.String = Field(nullable=True)
    generator_name: pl.String = Field(nullable=True)
    fault_level_replacement_cost_m: pl.String = Field(nullable=True)
