"""Pandera schemas for ISP 2025 tables.

Auto-generated by scripts/generate_isp2025_schemas.py — edit as needed.
"""

import pandera.polars as pa
import polars as pl


class ExistingGenerators(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    fuel_type: pl.String | None = pa.Field(alias="Fuel Type")
    region: pl.String | None = pa.Field(alias="Region")
    sub_region: pl.String | None = pa.Field(alias="Sub-region")
    rez_location: pl.String | None = pa.Field(alias="REZ Location")
    rez_id: pl.String | None = pa.Field(alias="REZ ID")
    status: pl.String | None = pa.Field(alias="Status")
    regional_build_cost_zone: pl.String | None = pa.Field(alias="Regional build cost zone")
    maximum_capacity_mw: pl.Float64 | None = pa.Field(alias="Maximum capacity (MW)")
    storage_capacity_mwh: pl.Float64 | None = pa.Field(alias="Storage capacity (MWh)")
    summer_peak_rating_mw: pl.String | None = pa.Field(alias="Summer peak rating (MW)")
    summer_typical_rating_mw: pl.String | None = pa.Field(alias="Summer typical rating (MW)")
    winter_rating_mw: pl.Float64 | None = pa.Field(alias="Winter rating (MW)")
    minimum_stable_limit: pl.String | None = pa.Field(alias="Minimum Stable Limit")
    no_load_heat_rate: pl.String | None = pa.Field(alias="No-Load  Heat Rate")
    marginal_heat_rate: pl.String | None = pa.Field(alias="Marginal Heat Rate")
    pumping_efficiency: pl.String | None = pa.Field(alias="Pumping efficiency (%)")
    charge_efficiency: pl.String | None = pa.Field(alias="Charge efficiency (%)")
    discharge_efficiency: pl.String | None = pa.Field(alias="Discharge efficiency (%)")
    allowable_max_state_of_charge: pl.String | None = pa.Field(
        alias="Allowable max state of charge (%)"
    )
    allowable_min_state_of_charge: pl.String | None = pa.Field(
        alias="Allowable min state of charge (%)"
    )
    round_trip_efficiency: pl.String | None = pa.Field(alias="Round trip efficiency (%)")
    annual_degradation: pl.String | None = pa.Field(alias="Annual degradation (%)")
    max_ramp_up_mw_min: pl.String | None = pa.Field(alias="Max Ramp Up\n(MW/min)")
    max_ramp_down_mw_min: pl.String | None = pa.Field(alias="Max Ramp Down\n(MW/min)")
    maintenance_proportion_of_time_out: pl.String | None = pa.Field(
        alias="Maintenance - Proportion of time out (%)"
    )
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.String | None = pa.Field(
        alias="Maintenance - Equivalent average days per year on planned outage"
    )
    forced_outage_rate: pl.String | None = pa.Field(alias="Forced Outage Rate (%)")
    unnamed_30: pl.String | None = pa.Field(alias="__UNNAMED__30")
    mean_time_to_repair_hrs: pl.String | None = pa.Field(alias="Mean time to repair (hrs) ")
    unnamed_32: pl.String | None = pa.Field(alias="__UNNAMED__32")
    derating_factor: pl.String | None = pa.Field(alias="Derating Factor (%) ")
    fom_kw_annum: pl.Float64 | None = pa.Field(alias="FOM ($/kW/annum)")
    vom_mwh_sent_out: pl.Float64 | None = pa.Field(alias="VOM \n($/MWh sent-out)")
    heat_rate_gj_mwh_hhv_s_o: pl.Float64 | None = pa.Field(alias="Heat rate\n(GJ/MWh HHV s.o.)")
    fuel_cost_gj: pl.String | None = pa.Field(alias="Fuel cost ($/GJ)")
    scope_1_emissions_kg_mwh: pl.String | None = pa.Field(alias="Scope 1 Emissions (kg/MWh)")
    mlf: pl.Float64 | None = pa.Field(alias="MLF")
    auxiliary_load_of_generation: pl.Float64 | None = pa.Field(
        alias="Auxiliary load (% of generation)"
    )
    srmc_mwh: pl.Float64 | None = pa.Field(alias="SRMC ($/MWh)")
    expected_closure_year_calendar_year: pl.Float64 | None = pa.Field(
        alias="Expected Closure Year (Calendar year)"
    )
    retirement_rehabilitation_cost_mw: pl.Float64 | None = pa.Field(
        alias="Retirement / Rehabilitation cost \n($/MW)"
    )
    fault_level_replacement_cost_m: pl.String | None = pa.Field(
        alias="Fault Level Replacement Cost ($M)"
    )


class NewEntrantGenerators(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    fuel_type: pl.String | None = pa.Field(alias="Fuel Type")
    region: pl.String | None = pa.Field(alias="Region")
    sub_region: pl.String | None = pa.Field(alias="Sub-region")
    rez_location: pl.String | None = pa.Field(alias="REZ location")
    rez_id: pl.String | None = pa.Field(alias="REZ ID")
    status: pl.String | None = pa.Field(alias="Status")
    regional_build_cost_zone: pl.String | None = pa.Field(alias="Regional build cost zone")
    maximum_capacity_mw: pl.Float64 | None = pa.Field(alias="Maximum capacity (MW)")
    storage_capacity_hours: pl.Float64 | None = pa.Field(alias="Storage capacity (hours)")
    seasonal_rating: pl.String | None = pa.Field(alias="Seasonal rating")
    unnamed_13: pl.String | None = pa.Field(alias="__UNNAMED__13")
    unnamed_14: pl.String | None = pa.Field(alias="__UNNAMED__14")
    min_stable_level_of_nameplate: pl.Float64 | None = pa.Field(
        alias="Min Stable Level \n(% of nameplate)"
    )
    no_load_heat_rate: pl.Float64 | None = pa.Field(alias="No-Load  Heat Rate")
    marginal_heat_rate: pl.Float64 | None = pa.Field(alias="Marginal Heat Rate")
    pumping_efficiency: pl.String | None = pa.Field(alias="Pumping efficiency (%)")
    charge_efficiency: pl.String | None = pa.Field(alias="Charge efficiency (%)")
    discharge_efficiency: pl.String | None = pa.Field(alias="Discharge efficiency (%)")
    allowable_max_state_of_charge: pl.String | None = pa.Field(
        alias="Allowable max state of charge (%)"
    )
    allowable_min_state_of_charge: pl.String | None = pa.Field(
        alias="Allowable min state of charge (%)"
    )
    round_trip_efficiency: pl.String | None = pa.Field(alias="Round trip efficiency (%)")
    annual_degradation: pl.String | None = pa.Field(alias="Annual degradation (%)")
    max_ramp_up_mw_min: pl.String | None = pa.Field(alias="Max Ramp Up\n(MW/min)")
    max_ramp_down_mw_min: pl.String | None = pa.Field(alias="Max Ramp Down\n(MW/min)")
    maintenance_proportion_of_time_out: pl.Float64 | None = pa.Field(
        alias="Maintenance - Proportion of time out (%)"
    )
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 | None = pa.Field(
        alias="Maintenance - Equivalent average days per year on planned outage"
    )
    forced_outage_rate: pl.String | None = pa.Field(alias="Forced Outage Rate (%)")
    unnamed_30: pl.String | None = pa.Field(alias="__UNNAMED__30")
    mean_time_to_repair_hrs: pl.String | None = pa.Field(alias="Mean time to repair (hrs) ")
    unnamed_32: pl.String | None = pa.Field(alias="__UNNAMED__32")
    derating_factor: pl.String | None = pa.Field(alias="Derating Factor (%) ")
    locational_cost_factors: pl.Float64 | None = pa.Field(alias="Locational Cost Factors")
    fom_kw_annum: pl.Float64 | None = pa.Field(alias="FOM ($/kW/annum)")
    vom_mwh_sent_out: pl.Float64 | None = pa.Field(alias="VOM \n($/MWh sent-out)")
    heat_rate_gj_mwh_hhv_s_o: pl.Float64 | None = pa.Field(alias="Heat rate\n(GJ/MWh HHV s.o.)")
    fuel_cost_gj_1: pl.String | None = pa.Field(alias="Fuel cost ($/GJ)1")
    scope_1_emissions_kg_mwh: pl.String | None = pa.Field(alias="Scope 1 Emissions (kg/MWh)")
    mlf: pl.Float64 | None = pa.Field(alias="MLF")
    auxiliary_load_of_generation: pl.Float64 | None = pa.Field(
        alias="Auxiliary load (% of generation)"
    )
    srmc_mwh: pl.Float64 | None = pa.Field(alias="SRMC ($/MWh)")
    expected_closure_year_calendar_year: pl.String | None = pa.Field(
        alias="Expected Closure Year (Calendar year)"
    )
    retirement_rehabilitation_cost_mw: pl.Float64 | None = pa.Field(
        alias="Retirement / Rehabilitation cost \n($/MW)"
    )
    build_cost_kw: pl.String | None = pa.Field(alias="Build cost ($/kW)")
    connection_cost_kw: pl.String | None = pa.Field(alias="Connection cost ($/kW)")
    efficient_level_of_system_strength_cost_kw: pl.String | None = pa.Field(
        alias="Efficient Level of System Strength Cost ($/kW)"
    )
    balance_of_plant_consumption: pl.String | None = pa.Field(
        alias="Balance of Plant consumption (%)"
    )
    wacc: pl.String | None = pa.Field(alias="WACC (%)")
    total_lead_time_years: pl.Float64 | None = pa.Field(alias="Total lead time (years)")
    economic_life_years: pl.Float64 | None = pa.Field(alias="Economic life (years)")
    technical_life_years: pl.Float64 | None = pa.Field(alias="Technical life (years)")


class NewElectrolyserData(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    fuel_type: pl.String | None = pa.Field(alias="Fuel Type")
    region: pl.String | None = pa.Field(alias="Region")
    sub_region: pl.String | None = pa.Field(alias="Sub-region")
    rez_location: pl.String | None = pa.Field(alias="REZ location")
    rez_id: pl.String | None = pa.Field(alias="REZ ID")
    status: pl.String | None = pa.Field(alias="Status")
    regional_build_cost_zone: pl.String | None = pa.Field(alias="Regional build cost zone")
    maximum_capacity_mw: pl.Float64 | None = pa.Field(alias="Maximum capacity (MW)")
    storage_capacity_hours: pl.String | None = pa.Field(alias="Storage capacity (hours)")
    seasonal_rating: pl.String | None = pa.Field(alias="Seasonal rating")
    unnamed_13: pl.String | None = pa.Field(alias="__UNNAMED__13")
    unnamed_14: pl.String | None = pa.Field(alias="__UNNAMED__14")
    min_stable_level_of_nameplate: pl.Float64 | None = pa.Field(
        alias="Min Stable Level \n(% of nameplate)"
    )
    maintenance_proportion_of_time_out: pl.Float64 | None = pa.Field(
        alias="Maintenance - Proportion of time out (%)"
    )
    maintenance_equivalent_average_days_per_year_on_planned_outage: pl.Float64 | None = pa.Field(
        alias="Maintenance - Equivalent average days per year on planned outage"
    )
    forced_outage_rate: pl.String | None = pa.Field(alias="Forced Outage Rate (%)")
    unnamed_19: pl.String | None = pa.Field(alias="__UNNAMED__19")
    mean_time_to_repair_hrs: pl.String | None = pa.Field(alias="Mean time to repair (hrs) ")
    unnamed_21: pl.String | None = pa.Field(alias="__UNNAMED__21")
    derating_factor: pl.String | None = pa.Field(alias="Derating Factor (%) ")
    locational_cost_factors: pl.Float64 | None = pa.Field(alias="Locational Cost Factors")
    fom_kw_annum: pl.Float64 | None = pa.Field(alias="FOM ($/kW/annum)")
    vom_mwh_sent_out: pl.Float64 | None = pa.Field(alias="VOM \n($/MWh sent-out)")
    heat_rate_gj_mwh_hhv_s_o: pl.Float64 | None = pa.Field(alias="Heat rate\n(GJ/MWh HHV s.o.)")
    scope_1_emissions_kg_mwh: pl.String | None = pa.Field(alias="Scope 1 Emissions (kg/MWh)")
    mlf: pl.Float64 | None = pa.Field(alias="MLF")
    auxiliary_load_of_generation: pl.Float64 | None = pa.Field(
        alias="Auxiliary load (% of generation)"
    )
    expected_closure_year_calendar_year: pl.String | None = pa.Field(
        alias="Expected Closure Year (Calendar year)"
    )
    retirement_rehabilitation_cost_mw: pl.Float64 | None = pa.Field(
        alias="Retirement / Rehabilitation cost \n($/MW)"
    )
    build_cost_kw: pl.String | None = pa.Field(alias="Build cost ($/kW)")
    associated_pipeline_cost_kw: pl.String | None = pa.Field(
        alias="Associated Pipeline Cost ($/kW)"
    )
    connection_cost_kw: pl.String | None = pa.Field(alias="Connection cost ($/kW)")
    efficient_level_of_system_strength_cost_kw: pl.String | None = pa.Field(
        alias="Efficient Level of System Strength Cost ($/kW)"
    )
    balance_of_plant_consumption: pl.String | None = pa.Field(
        alias="Balance of Plant consumption (%)"
    )
    wacc: pl.String | None = pa.Field(alias="WACC (%)")
    total_lead_time_years: pl.Float64 | None = pa.Field(alias="Total lead time (years)")
    economic_life_years: pl.Float64 | None = pa.Field(alias="Economic life (years)")
    technical_life_years: pl.Float64 | None = pa.Field(alias="Technical life (years)")
    minimum_capacity_utilization_factor: pl.String | None = pa.Field(
        alias="Minimum Capacity/Utilization Factor (%)"
    )


class StorageProperties(pa.DataFrameModel):
    technology: pl.String | None = pa.Field(alias="Technology")
    maximum_power1: pl.String | None = pa.Field(alias="Maximum power1")
    energy_capacity2: pl.String | None = pa.Field(alias="Energy capacity2")
    charge_efficiency: pl.String | None = pa.Field(alias="Charge efficiency")
    discharge_efficiency: pl.String | None = pa.Field(alias="Discharge efficiency")
    allowable_max_state_of_charge: pl.String | None = pa.Field(
        alias="Allowable max state of charge"
    )
    allowable_min_state_of_charge: pl.String | None = pa.Field(
        alias="Allowable min state of charge"
    )
    round_trip_efficiency3: pl.String | None = pa.Field(alias="Round trip efficiency3")
    annual_degradation4: pl.String | None = pa.Field(alias="Annual degradation4")


class MaximumCapacity(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    status5: pl.String | None = pa.Field(alias="Status5")
    technology: pl.String | None = pa.Field(alias="Technology")
    region: pl.String | None = pa.Field(alias="Region")
    installed_capacity_mw: pl.Float64 | None = pa.Field(alias="Installed capacity (MW)")
    storage_capacity_mwh: pl.Float64 | None = pa.Field(alias="Storage Capacity (MWh)")
    commissioning_date: pl.Datetime | None = pa.Field(alias="Commissioning date")
    policy: pl.String | None = pa.Field(alias="Policy")
    unnamed_9: pl.String | None = pa.Field(alias="__UNNAMED__9")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    unit_size_mw: pl.Float64 | None = pa.Field(alias="Unit size (MW)")
    number_of_units: pl.Float64 | None = pa.Field(alias="Number of units")
    total_plant_size_mw: pl.Float64 | None = pa.Field(alias="Total plant size (MW)")


class SeasonalRatings(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    status: pl.String | None = pa.Field(alias="Status")
    region: pl.String | None = pa.Field(alias="Region")
    col_2024_25: pl.Float64 | None = pa.Field(alias="2024-25")
    col_2025_26: pl.Float64 | None = pa.Field(alias="2025-26")
    col_2026_27: pl.Float64 | None = pa.Field(alias="2026-27")
    col_2027_28: pl.Float64 | None = pa.Field(alias="2027-28")
    col_2028_29: pl.Float64 | None = pa.Field(alias="2028-29")
    col_2029_30: pl.Float64 | None = pa.Field(alias="2029-30")
    col_2030_31: pl.Float64 | None = pa.Field(alias="2030-31")
    col_2031_32: pl.Float64 | None = pa.Field(alias="2031-32")
    col_2032_33: pl.Float64 | None = pa.Field(alias="2032-33")
    col_2033_34: pl.Float64 | None = pa.Field(alias="2033-34")
    col_2024_25_1: pl.Float64 | None = pa.Field(alias="2024-25_1")
    col_2025_26_1: pl.Float64 | None = pa.Field(alias="2025-26_1")
    col_2026_27_1: pl.Float64 | None = pa.Field(alias="2026-27_1")
    col_2027_28_1: pl.Float64 | None = pa.Field(alias="2027-28_1")
    col_2028_29_1: pl.Float64 | None = pa.Field(alias="2028-29_1")
    col_2029_30_1: pl.Float64 | None = pa.Field(alias="2029-30_1")
    col_2030_31_1: pl.Float64 | None = pa.Field(alias="2030-31_1")
    col_2031_32_1: pl.Float64 | None = pa.Field(alias="2031-32_1")
    col_2032_33_1: pl.Float64 | None = pa.Field(alias="2032-33_1")
    col_2033_34_1: pl.Float64 | None = pa.Field(alias="2033-34_1")
    col_2024: pl.Float64 | None = pa.Field(alias="2024")
    col_2025: pl.Float64 | None = pa.Field(alias="2025")
    col_2026: pl.Float64 | None = pa.Field(alias="2026")
    col_2027: pl.Float64 | None = pa.Field(alias="2027")
    col_2028: pl.Float64 | None = pa.Field(alias="2028")
    col_2029: pl.Float64 | None = pa.Field(alias="2029")
    col_2030: pl.Float64 | None = pa.Field(alias="2030")
    col_2031: pl.Float64 | None = pa.Field(alias="2031")
    col_2032: pl.Float64 | None = pa.Field(alias="2032")
    col_2033: pl.Float64 | None = pa.Field(alias="2033")


class Maintenance(pa.DataFrameModel):
    generator_type: pl.String | None = pa.Field(alias="Generator type")
    proportion_of_time_out: pl.Float64 | None = pa.Field(alias="Proportion of time out (%)")
    equivalent_average_days_per_year_on_planned_outage: pl.Float64 | None = pa.Field(
        alias="Equivalent average days per year on planned outage"
    )
    unnamed_3: pl.String | None = pa.Field(alias="__UNNAMED__3")
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    proportion_of_time_out_1: pl.Float64 | None = pa.Field(alias="Proportion of time out (%)_1")
    equivalent_average_days_per_year_on_planned_outage_1: pl.Float64 | None = pa.Field(
        alias="Equivalent average days per year on planned outage "
    )


class GeneratorReliability(pa.DataFrameModel):
    fuel_type: pl.String | None = pa.Field(alias="Fuel type")
    property: pl.String | None = pa.Field(alias="Property")
    col_2025_26: pl.String | None = pa.Field(alias="2025-26")
    col_2026_27: pl.String | None = pa.Field(alias="2026-27")
    col_2027_28: pl.String | None = pa.Field(alias="2027-28")
    col_2028_29: pl.String | None = pa.Field(alias="2028-29")
    col_2029_30: pl.String | None = pa.Field(alias="2029-30")
    col_2030_31: pl.String | None = pa.Field(alias="2030-31")
    col_2031_32: pl.String | None = pa.Field(alias="2031-32")
    col_2032_33: pl.String | None = pa.Field(alias="2032-33")
    col_2033_34: pl.String | None = pa.Field(alias="2033-34")
    col_2034_35: pl.String | None = pa.Field(alias="2034-35")


class Retirement(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    status: pl.String | None = pa.Field(alias="Status")
    expected_closure_year_calendar_year: pl.String | None = pa.Field(
        alias="Expected Closure Year (Calendar year)"
    )
    col5: pl.String | None = pa.Field(alias="_col5")


class RetirementCosts(pa.DataFrameModel):
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    retirement_mw: pl.String | None = pa.Field(alias="Retirement ($/MW)")


class HeatRates(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology: pl.String | None = pa.Field(alias="Technology")
    heat_rate_gj_mwh: pl.Float64 | None = pa.Field(alias="Heat rate (GJ/MWh)")
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    technology_1: pl.String | None = pa.Field(alias="Technology_1")
    heat_rate_gj_mwh_1: pl.Float64 | None = pa.Field(alias="Heat rate (GJ/MWh)_1")


class Auxiliary(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology: pl.String | None = pa.Field(alias="Technology")
    auxiliary_load_of_generation: pl.Float64 | None = pa.Field(
        alias="Auxiliary load (% of generation)"
    )
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    generator: pl.String | None = pa.Field(alias="Generator")
    auxiliary_load_of_generation_1: pl.Float64 | None = pa.Field(
        alias="Auxiliary load (% of generation)_1"
    )


class EmissionsIntensity(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology: pl.String | None = pa.Field(alias="Technology")
    scope_1_emissions_intensity_kg_mwh_as_gen: pl.Float64 | None = pa.Field(
        alias="Scope 1 emissions intensity (kg/MWh as-gen)"
    )
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    technology_1: pl.String | None = pa.Field(alias="Technology_1")
    scope_1_emissions_intensity_kg_mwh_as_gen_1: pl.Float64 | None = pa.Field(
        alias="Scope 1 emissions intensity (kg/MWh as-gen)_1"
    )


class FixedOpex(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology: pl.String | None = pa.Field(alias="Technology")
    fixed_opex_kw_year: pl.Float64 | None = pa.Field(alias="Fixed OPEX\n($/kW/year)")
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    base_value_kw_year: pl.Float64 | None = pa.Field(alias="Base value ($/kW/year))")
    unit: pl.String | None = pa.Field(alias="Unit")


class VariableOpex(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station_technology: pl.String | None = pa.Field(alias="Power Station / Technology")
    technology: pl.String | None = pa.Field(alias="Technology")
    variable_opex_mwh_sent_out_1: pl.Float64 | None = pa.Field(
        alias="Variable OPEX\n($/MWh sent out)1"
    )
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    generator: pl.String | None = pa.Field(alias="Generator")
    base_value: pl.Float64 | None = pa.Field(alias="Base value")


class AffineHeatRates(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    no_load_heat_input_gj_h: pl.Float64 | None = pa.Field(alias="No load heat input (GJ/h)")
    marginal_heat_rate_gj_mwh: pl.Float64 | None = pa.Field(alias="Marginal heat rate (GJ/MWh)")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    technology: pl.String | None = pa.Field(alias="Technology")
    unit_nominal_capacity_mw: pl.Float64 | None = pa.Field(alias="Unit nominal capacity (MW)")
    no_load_heat_input_gj_h_1: pl.Float64 | None = pa.Field(alias="No load heat input (GJ/h)_1")
    marginal_heat_rate_gj_mwh_1: pl.Float64 | None = pa.Field(alias="Marginal heat rate (GJ/MWh)_1")


class MaxRampRates(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    max_ramp_up_mw_min: pl.String | None = pa.Field(alias="Max Ramp Up\n(MW/min)")
    max_ramp_down_mw_min: pl.String | None = pa.Field(alias="Max Ramp Down\n(MW/min)")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    technology: pl.String | None = pa.Field(alias="Technology")
    max_ramp_up_mw_min_1: pl.String | None = pa.Field(alias="Max Ramp Up\n(MW/min)_1")
    max_ramp_down_mw_min_1: pl.String | None = pa.Field(alias="Max Ramp Down\n(MW/min)_1")


class CoalMinStableLevel(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    minimum_stable_level_mw: pl.String | None = pa.Field(alias="Minimum Stable Level (MW)")
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")


class GpgMinStableLevel(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    technology_type: pl.String | None = pa.Field(alias="Technology Type")
    min_stable_level_mw: pl.Float64 | None = pa.Field(alias="Min Stable Level (MW)")
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    technology: pl.String | None = pa.Field(alias="Technology")
    min_stable_level_of_nameplate: pl.Float64 | None = pa.Field(
        alias="Min Stable Level \n(% of nameplate)"
    )


class LeadTimeProjectLife(pa.DataFrameModel):
    technology: pl.String | None = pa.Field(alias="Technology")
    lead_time_for_development_years_1_2: pl.Float64 | None = pa.Field(
        alias="Lead time for development (years)1, 2"
    )
    lead_time_years_3: pl.Float64 | None = pa.Field(alias="Lead time (years)3")
    construction_time_years: pl.Float64 | None = pa.Field(alias="Construction time (years)")
    total_lead_time_years_4_7: pl.Float64 | None = pa.Field(alias="Total lead time (years)4,7")
    economic_life_years_5: pl.Float64 | None = pa.Field(alias="Economic life (years)5")
    technical_life_years_6: pl.Float64 | None = pa.Field(alias="Technical life (years)6")


class FinancialParameters(pa.DataFrameModel):
    unnamed_0: pl.String | None = pa.Field(alias="__UNNAMED__0")
    note: pl.String | None = pa.Field(alias="Note")
    lower_bound: pl.String | None = pa.Field(alias="Lower Bound")
    central: pl.String | None = pa.Field(alias="Central")
    upper_bound: pl.String | None = pa.Field(alias="Upper Bound")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")


class GasSystemProperties(pa.DataFrameModel):
    name: pl.String | None = pa.Field(alias="Name")
    status: pl.String | None = pa.Field(alias="Status")
    location: pl.String | None = pa.Field(alias="Location")
    capacity_tj_per_day: pl.String | None = pa.Field(alias="Capacity (TJ per day) ")
    source: pl.String | None = pa.Field(alias="Source")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    unnamed_6: pl.String | None = pa.Field(alias="__UNNAMED__6")


class RenewableEnergyZones(pa.DataFrameModel):
    id: pl.String | None = pa.Field(alias="ID")
    name: pl.String | None = pa.Field(alias="Name")
    nem_region: pl.String | None = pa.Field(alias="NEM region")
    isp_sub_region: pl.String | None = pa.Field(alias="ISP sub-region")
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    unnamed_6: pl.String | None = pa.Field(alias="__UNNAMED__6")


class NetworkCapability(pa.DataFrameModel):
    flow_paths: pl.String | None = pa.Field(alias="Flow Paths")
    forward_direction_capability_approximation_mw_notes_1_2_3: pl.String | None = pa.Field(
        alias="Forward direction capability approximation (MW) - Notes 1,2&3"
    )
    unnamed_2: pl.String | None = pa.Field(alias="__UNNAMED__2")
    unnamed_3: pl.String | None = pa.Field(alias="__UNNAMED__3")
    reverse_direction_capability_approximation_mw_notes_1_2_3: pl.String | None = pa.Field(
        alias="Reverse direction capability approximation (MW) - Notes 1,2&3"
    )
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    unnamed_6: pl.String | None = pa.Field(alias="__UNNAMED__6")
    dominant_constraints: pl.String | None = pa.Field(alias="Dominant constraints")
    unnamed_8: pl.String | None = pa.Field(alias="__UNNAMED__8")
    notes: pl.String | None = pa.Field(alias="Notes")
    unnamed_10: pl.String | None = pa.Field(alias="__UNNAMED__10")
    unnamed_11: pl.String | None = pa.Field(alias="__UNNAMED__11")
    unnamed_12: pl.String | None = pa.Field(alias="__UNNAMED__12")
    unnamed_13: pl.String | None = pa.Field(alias="__UNNAMED__13")
    unnamed_14: pl.String | None = pa.Field(alias="__UNNAMED__14")
    unnamed_15: pl.String | None = pa.Field(alias="__UNNAMED__15")
    unnamed_16: pl.String | None = pa.Field(alias="__UNNAMED__16")
    unnamed_17: pl.String | None = pa.Field(alias="__UNNAMED__17")
    unnamed_18: pl.String | None = pa.Field(alias="__UNNAMED__18")
    unnamed_19: pl.String | None = pa.Field(alias="__UNNAMED__19")
    unnamed_20: pl.String | None = pa.Field(alias="__UNNAMED__20")


class NetworkLosses(pa.DataFrameModel):
    flow_path: pl.String | None = pa.Field(alias="Flow Path")
    interconnector_flow_path_name: pl.String | None = pa.Field(
        alias="Interconnector/Flow path Name"
    )
    from_region_sub_region: pl.String | None = pa.Field(alias="From region/sub-region")
    to_region_subregion: pl.String | None = pa.Field(alias="To region/Subregion")
    loss_equation: pl.String | None = pa.Field(alias="Loss Equation")
    mlf_equation: pl.String | None = pa.Field(alias="MLF Equation")
    from_region_loss_proportion: pl.String | None = pa.Field(alias="From region loss proportion")
    to_region_loss_proportion: pl.String | None = pa.Field(alias="To region loss proportion")
    notes: pl.String | None = pa.Field(alias="Notes")


class TransmissionReliability(pa.DataFrameModel):
    line_flowpath: pl.String | None = pa.Field(alias="Line/Flowpath")
    implementation: pl.String | None = pa.Field(alias="Implementation")
    unplanned_outage_rate: pl.Float64 | None = pa.Field(alias="Unplanned Outage Rate (%)")
    mean_time_to_repair: pl.Float64 | None = pa.Field(alias="Mean Time to Repair")


class ConnectionCost(pa.DataFrameModel):
    rez_id: pl.String | None = pa.Field(alias="REZ ID")
    rez_names: pl.String | None = pa.Field(alias="REZ names")
    region: pl.String | None = pa.Field(alias="Region")
    rez_network_voltage_kv: pl.String | None = pa.Field(alias="REZ network voltage (kV)")
    connection_capacity_mva: pl.String | None = pa.Field(alias="Connection capacity (MVA)")
    feeder_length_km: pl.String | None = pa.Field(alias="Feeder length (km)")
    total_cost_m: pl.String | None = pa.Field(alias="Total cost ($M)")
    kw: pl.String | None = pa.Field(alias="$/kW")
    notes: pl.String | None = pa.Field(alias="Notes")
    unnamed_9: pl.String | None = pa.Field(alias="__UNNAMED__9")
    unnamed_10: pl.String | None = pa.Field(alias="__UNNAMED__10")
    unnamed_11: pl.String | None = pa.Field(alias="__UNNAMED__11")
    unnamed_12: pl.String | None = pa.Field(alias="__UNNAMED__12")
    unnamed_13: pl.String | None = pa.Field(alias="__UNNAMED__13")
    unnamed_14: pl.String | None = pa.Field(alias="__UNNAMED__14")
    unnamed_15: pl.String | None = pa.Field(alias="__UNNAMED__15")
    unnamed_16: pl.String | None = pa.Field(alias="__UNNAMED__16")


class FlowPathAugmentation(pa.DataFrameModel):
    flow_path: pl.String | None = pa.Field(alias="Flow path")
    development_path: pl.String | None = pa.Field(alias="Development path")
    development_driver: pl.String | None = pa.Field(alias="Development driver")
    option_name: pl.String | None = pa.Field(alias="Option name")
    augmentation_description: pl.String | None = pa.Field(alias="Augmentation description")
    pre_requisite_options: pl.String | None = pa.Field(alias="Pre-requisite options")
    forward_direction_power_flow: pl.String | None = pa.Field(alias="Forward direction power flow")
    notional_transfer_level_increase_mw_note_same_increase_applies_to_all_transfer_limit_conditions_peak_demand_summer_typical_and_winter_reference: (
        pl.String | None
    ) = pa.Field(
        alias="Notional transfer level increase (MW) Note: Same increase applies to all transfer limit conditions (Peak demand, Summer typical and Winter reference)"
    )
    unnamed_8: pl.String | None = pa.Field(alias="__UNNAMED__8")
    indicative_cost_estimate_2025_million: pl.String | None = pa.Field(
        alias="Indicative cost estimate  ($2025, $ million)"
    )
    cost_estimate_source: pl.String | None = pa.Field(alias="Cost estimate source")
    cost_estimate_class: pl.String | None = pa.Field(alias="Cost estimate class")
    easement_length_km: pl.String | None = pa.Field(alias="Easement length (km)")
    lead_time_or_earliest_in_service_date: pl.String | None = pa.Field(
        alias="Lead time or earliest in service date"
    )
    additional_rez_transmission_capacity_provided: pl.String | None = pa.Field(
        alias="Additional REZ transmission capacity provided"
    )
    notes: pl.String | None = pa.Field(alias="Notes")


class RezAugmentations(pa.DataFrameModel):
    rez_constraint_id: pl.String | None = pa.Field(alias="REZ / constraint ID")
    rez_name: pl.String | None = pa.Field(alias="REZ name")
    option: pl.String | None = pa.Field(alias="Option")
    augmentation_description: pl.String | None = pa.Field(alias="Augmentation description")
    pre_requisite_options: pl.String | None = pa.Field(alias="Pre-requisite options")
    additional_network_capacity_mw: pl.String | None = pa.Field(
        alias="Additional network capacity (MW)"
    )
    additional_import_capacity_mw: pl.String | None = pa.Field(
        alias="Additional import capacity (MW)"
    )
    expected_cost_2025_million: pl.String | None = pa.Field(alias="Expected cost ($2025 million)")
    cost_estimate_source: pl.String | None = pa.Field(alias="Cost estimate source")
    cost_estimate_class: pl.String | None = pa.Field(alias="Cost estimate class")
    m_mw: pl.String | None = pa.Field(alias="$M/MW")
    easement_length_km: pl.String | None = pa.Field(alias="Easement length (km)")
    lead_time: pl.String | None = pa.Field(alias="Lead time")
    notes: pl.String | None = pa.Field(alias="Notes")


class BuildLimitsRez(pa.DataFrameModel):
    rez_id: pl.String | None = pa.Field(alias="REZ ID")
    rez_name: pl.String | None = pa.Field(alias="REZ Name")
    wind_generation_total_limits_mw: pl.String | None = pa.Field(
        alias="Wind generation total limits (MW)"
    )
    unnamed_3: pl.String | None = pa.Field(alias="__UNNAMED__3")
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    solar_pv_plus_solar_thermal_limits_mw: pl.String | None = pa.Field(
        alias="Solar PV plus Solar thermal Limits (MW)"
    )
    rez_resource_limit_violation_penalty_factor_m_mw: pl.String | None = pa.Field(
        alias="REZ resource limit violation penalty factor ($M/MW)"
    )
    land_use_limits_in_mw: pl.String | None = pa.Field(alias="Land use limits in MW")
    unnamed_9: pl.String | None = pa.Field(alias="__UNNAMED__9")
    land_use_limits_in_mw_accelerated_transition_scenario: pl.String | None = pa.Field(
        alias="Land use limits in MW\nAccelerated Transition scenario"
    )
    unnamed_11: pl.String | None = pa.Field(alias="__UNNAMED__11")
    land_area_km2_additional_table_note_1: pl.String | None = pa.Field(
        alias="Land area (km2) (additional table note 1)"
    )
    notes: pl.String | None = pa.Field(alias="Notes")


class BuildLimitsPhes(pa.DataFrameModel):
    name: pl.String | None = pa.Field(alias="Name")
    isp_sub_region: pl.String | None = pa.Field(alias="ISP Sub-region")
    region: pl.String | None = pa.Field(alias="Region")
    pumped_hydro_energy_storage_phes_limits_mw: pl.String | None = pa.Field(
        alias="Pumped Hydro Energy Storage (PHES) limits (MW)"
    )
    unnamed_4: pl.String | None = pa.Field(alias="__UNNAMED__4")
    unnamed_5: pl.String | None = pa.Field(alias="__UNNAMED__5")
    unnamed_6: pl.String | None = pa.Field(alias="__UNNAMED__6")
    unnamed_7: pl.String | None = pa.Field(alias="__UNNAMED__7")
    unnamed_8: pl.String | None = pa.Field(alias="__UNNAMED__8")
    unnamed_9: pl.String | None = pa.Field(alias="__UNNAMED__9")
    unnamed_10: pl.String | None = pa.Field(alias="__UNNAMED__10")
    unnamed_11: pl.String | None = pa.Field(alias="__UNNAMED__11")
    unnamed_12: pl.String | None = pa.Field(alias="__UNNAMED__12")
    unnamed_13: pl.String | None = pa.Field(alias="__UNNAMED__13")
    unnamed_14: pl.String | None = pa.Field(alias="__UNNAMED__14")
    unnamed_15: pl.String | None = pa.Field(alias="__UNNAMED__15")
    unnamed_16: pl.String | None = pa.Field(alias="__UNNAMED__16")
    unnamed_17: pl.String | None = pa.Field(alias="__UNNAMED__17")
    unnamed_18: pl.String | None = pa.Field(alias="__UNNAMED__18")
    unnamed_19: pl.String | None = pa.Field(alias="__UNNAMED__19")
    unnamed_20: pl.String | None = pa.Field(alias="__UNNAMED__20")
    unnamed_21: pl.String | None = pa.Field(alias="__UNNAMED__21")


class LocationalCostFactors(pa.DataFrameModel):
    cost_zone_rez_id: pl.String | None = pa.Field(alias="Cost zone / REZ ID")
    rez_name: pl.String | None = pa.Field(alias="REZ name")
    equipment_and_installation_costs: pl.String | None = pa.Field(
        alias="Equipment and installation costs"
    )
    fuel_connection_costs: pl.String | None = pa.Field(alias="Fuel connection costs")
    cost_of_land_and_development_2: pl.String | None = pa.Field(
        alias="Cost of land and development 2 "
    )
    installation_costs: pl.String | None = pa.Field(alias="Installation costs")
    o_m_costs_3: pl.String | None = pa.Field(alias="O&M costs 3")
    unnamed_7: pl.String | None = pa.Field(alias="__UNNAMED__7")
    unnamed_8: pl.String | None = pa.Field(alias="__UNNAMED__8")
    nem_regional_cost_zone_map: pl.String | None = pa.Field(alias="NEM Regional Cost Zone Map")
    unnamed_10: pl.String | None = pa.Field(alias="__UNNAMED__10")
    unnamed_11: pl.String | None = pa.Field(alias="__UNNAMED__11")
    unnamed_12: pl.String | None = pa.Field(alias="__UNNAMED__12")
    unnamed_13: pl.String | None = pa.Field(alias="__UNNAMED__13")
    unnamed_14: pl.String | None = pa.Field(alias="__UNNAMED__14")
    unnamed_15: pl.String | None = pa.Field(alias="__UNNAMED__15")
    unnamed_16: pl.String | None = pa.Field(alias="__UNNAMED__16")
    unnamed_17: pl.String | None = pa.Field(alias="__UNNAMED__17")
    unnamed_18: pl.String | None = pa.Field(alias="__UNNAMED__18")
    unnamed_19: pl.String | None = pa.Field(alias="__UNNAMED__19")
    unnamed_20: pl.String | None = pa.Field(alias="__UNNAMED__20")
    unnamed_21: pl.String | None = pa.Field(alias="__UNNAMED__21")
    unnamed_22: pl.String | None = pa.Field(alias="__UNNAMED__22")


class CapacityFactors(pa.DataFrameModel):
    rez_id_subregion: pl.String | None = pa.Field(alias="REZ ID / Subregion")
    rez_name_subregion_name: pl.String | None = pa.Field(alias="REZ Name / Subregion Name")
    technology: pl.String | None = pa.Field(alias="Technology")
    region: pl.String | None = pa.Field(alias="Region")
    col_2010_11: pl.Float64 | None = pa.Field(alias="2010-11")
    col_2011_12: pl.Float64 | None = pa.Field(alias="2011-12")
    col_2012_13: pl.Float64 | None = pa.Field(alias="2012-13")
    col_2013_14: pl.Float64 | None = pa.Field(alias="2013-14")
    col_2014_15: pl.Float64 | None = pa.Field(alias="2014-15")
    col_2015_16: pl.Float64 | None = pa.Field(alias="2015-16")
    col_2016_17: pl.Float64 | None = pa.Field(alias="2016-17")
    col_2017_18: pl.Float64 | None = pa.Field(alias="2017-18")
    col_2018_19: pl.Float64 | None = pa.Field(alias="2018-19")
    col_2019_20: pl.Float64 | None = pa.Field(alias="2019-20")
    col_2020_21: pl.Float64 | None = pa.Field(alias="2020-21")
    col_2021_22: pl.Float64 | None = pa.Field(alias="2021-22")
    col_2022_23: pl.Float64 | None = pa.Field(alias="2022-23")
    col_2023_24: pl.Float64 | None = pa.Field(alias="2023-24")
    col_2024_25: pl.Float64 | None = pa.Field(alias="2024-25")
    avg_of_reference_years: pl.Float64 | None = pa.Field(alias="Avg of reference years")
    comment: pl.String | None = pa.Field(alias="Comment")


class MarginalLossFactors(pa.DataFrameModel):
    iasr_id: pl.String | None = pa.Field(alias="IASR ID")
    tni_code: pl.String | None = pa.Field(alias="TNI Code")
    power_station: pl.String | None = pa.Field(alias="Power Station")
    status: pl.String | None = pa.Field(alias="Status")
    mlf: pl.String | None = pa.Field(alias="MLF")
    shadow_connection_point: pl.String | None = pa.Field(alias="Shadow connection point")
    generator_group: pl.String | None


class HydroSchemeInflows(pa.DataFrameModel):
    reference_year_fye: pl.String | None = pa.Field(alias="Reference Year (FYE)")
    jul: pl.String | None = pa.Field(alias="Jul")
    aug: pl.String | None = pa.Field(alias="Aug")
    sep: pl.String | None = pa.Field(alias="Sep")
    oct: pl.String | None = pa.Field(alias="Oct")
    nov: pl.String | None = pa.Field(alias="Nov")
    dec: pl.String | None = pa.Field(alias="Dec")
    jan: pl.String | None = pa.Field(alias="Jan")
    feb: pl.String | None = pa.Field(alias="Feb")
    mar: pl.String | None = pa.Field(alias="Mar")
    apr: pl.String | None = pa.Field(alias="Apr")
    may: pl.String | None = pa.Field(alias="May")
    jun: pl.String | None = pa.Field(alias="Jun")
    annual_total: pl.String | None = pa.Field(alias="Annual Total")
    unnamed_14: pl.String | None = pa.Field(alias="__UNNAMED__14")
    unnamed_15: pl.String | None = pa.Field(alias="__UNNAMED__15")
    unnamed_16: pl.String | None = pa.Field(alias="__UNNAMED__16")
    unnamed_17: pl.String | None = pa.Field(alias="__UNNAMED__17")
    unnamed_18: pl.String | None = pa.Field(alias="__UNNAMED__18")


class BuildCosts(pa.DataFrameModel):
    technology1: pl.String | None = pa.Field(alias="Technology1")
    gencost_scenario: pl.String | None = pa.Field(alias="GenCost Scenario")
    iasr_scenario: pl.String | None = pa.Field(alias="IASR Scenario")
    source: pl.String | None = pa.Field(alias="Source")
    year: pl.String | None
    value: pl.Float64 | None


class ConnectionCostForecasts(pa.DataFrameModel):
    rez_id: pl.String | None = pa.Field(alias="REZ ID")
    rez_names: pl.String | None = pa.Field(alias="REZ names")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    notes: pl.String | None = pa.Field(alias="Notes")
    year: pl.String | None
    value: pl.Float64 | None


class FlowPathCostForecasts(pa.DataFrameModel):
    flow_path: pl.String | None = pa.Field(alias="Flow path")
    option: pl.String | None = pa.Field(alias="Option")
    status: pl.String | None = pa.Field(alias="Status")
    year: pl.String | None
    value: pl.Float64 | None


class RezCostForecasts(pa.DataFrameModel):
    rez_constraint_id: pl.String | None = pa.Field(alias="REZ / Constraint ID")
    rez_name: pl.String | None = pa.Field(alias="REZ name")
    option: pl.String | None = pa.Field(alias="Option")
    status: pl.String | None = pa.Field(alias="Status")
    year: pl.String | None
    value: pl.Float64 | None


class DistributionCostForecasts(pa.DataFrameModel):
    distributon_network_service_provider: pl.String | None = pa.Field(
        alias="Distributon Network Service Provider "
    )
    distribution_network_upgrade_tranche: pl.String | None = pa.Field(
        alias="Distribution network upgrade tranche"
    )
    scenario: pl.String | None = pa.Field(alias="Scenario")
    notes: pl.String | None = pa.Field(alias="Notes")
    year: pl.String | None
    value: pl.Float64 | None


class CoalBiomassPrice(pa.DataFrameModel):
    generator: pl.String | None = pa.Field(alias="Generator")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class GasLiquidH2Price(pa.DataFrameModel):
    col_1: pl.Float64 | None = pa.Field(alias="1")
    generator: pl.String | None = pa.Field(alias="Generator")
    gas_price_scenario: pl.String | None = pa.Field(alias="Gas price scenario")
    year: pl.String | None
    value: pl.Float64 | None


class RooftopPv(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class Pvnsg(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class Onsg(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class BatteryPluginEvs(pa.DataFrameModel):
    region: pl.String | None = pa.Field(alias="Region")
    subregion: pl.String | None = pa.Field(alias="Subregion")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class FuelCellEvs(pa.DataFrameModel):
    region: pl.String | None = pa.Field(alias="Region")
    subregion: pl.String | None = pa.Field(alias="Subregion")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class EvV2g(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class Dsp(pa.DataFrameModel):
    region: pl.String | None = pa.Field(alias="Region")
    price_band: pl.String | None = pa.Field(alias="Price band")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    season: pl.String | None = pa.Field(alias="Season")
    year: pl.String | None
    value: pl.Float64 | None


class DataCentreForecasts(pa.DataFrameModel):
    scenario: pl.String | None
    state: pl.String | None
    year: pl.String | None
    value: pl.Float64 | None


class Electrification(pa.DataFrameModel):
    scenario: pl.String | None
    state: pl.String | None
    year: pl.String | None
    value: pl.Float64 | None


class EmbeddedEnergyStorages(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class AggregatedEnergyStorages(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class EndUseFuelConsumption(pa.DataFrameModel):
    scenario: pl.String | None
    fuel_sector: pl.String | None
    year: pl.String | None
    value: pl.Float64 | None


class ApplianceUptake(pa.DataFrameModel):
    scenario: pl.String | None
    state: pl.String | None
    year: pl.String | None
    value: pl.Float64 | None


class ElecRetailPriceIndices(pa.DataFrameModel):
    unnamed_0: pl.String | None = pa.Field(alias="__UNNAMED__0")
    year: pl.String | None
    value: pl.Float64 | None


class ConnectionsForecasts(pa.DataFrameModel):
    scenario: pl.String | None
    state: pl.String | None
    year: pl.String | None
    value: pl.Float64 | None


class EnergyEfficiency(pa.DataFrameModel):
    section: pl.String | None
    scenario: pl.String | None
    state: pl.String | None
    year: pl.String | None
    value: pl.Float64 | None


class HydrogenDemandDomestic(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class HydrogenDemandExport(pa.DataFrameModel):
    isp_subregion: pl.String | None = pa.Field(alias="ISP Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class HydrogenMonthlyProfiles(pa.DataFrameModel):
    month: pl.String | None = pa.Field(alias="Month")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class WaterForHydrogen(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class DesalinationDemandH2(pa.DataFrameModel):
    subregion: pl.String | None = pa.Field(alias="Subregion")
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class H2GpgLimit(pa.DataFrameModel):
    region: pl.String | None = pa.Field(alias="Region")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    year: pl.String | None
    value: pl.Float64 | None


class BuildCostHydrogenPipeline(pa.DataFrameModel):
    electrolyser_pipeline: pl.String | None = pa.Field(alias="Electrolyser Pipeline")
    demand_location: pl.String | None = pa.Field(alias="Demand location")
    scenario: pl.String | None = pa.Field(alias="Scenario")
    rez: pl.String | None = pa.Field(alias="REZ")
    length_km: pl.Float64 | None = pa.Field(alias="Length (km)")
    year: pl.String | None
    value: pl.Float64 | None


class GpgEmissionsReduction(pa.DataFrameModel):
    unnamed_0: pl.String | None = pa.Field(alias="__UNNAMED__0")
    year: pl.String | None
    value: pl.Float64 | None


class FuelPriceSummary(pa.DataFrameModel):
    generator: pl.String | None = pa.Field(alias="Generator")
    status: pl.String | None = pa.Field(alias="Status")
    region: pl.String | None = pa.Field(alias="Region")
    fuel_type: pl.String | None = pa.Field(alias="Fuel type")
    rez_sub_region: pl.String | None = pa.Field(alias="REZ/Sub-region")
    fuel_cost_mapping: pl.String | None = pa.Field(alias="Fuel cost mapping")
    year: pl.String | None
    price_gj: pl.Float64 | None
    generator_status: pl.String | None


class EconomicGrowthForecasts(pa.DataFrameModel):
    metric: pl.String | None
    scenario: pl.String | None
    state: pl.String | None
    year: pl.String | None
    value: pl.Float64 | None


class PowerSystemSecurity(pa.DataFrameModel):
    duid: pl.String | None = pa.Field(alias="DUID")
    generator_name: pl.String | None = pa.Field(alias="Generator name")
    fault_level_replacement_cost_m: pl.String | None = pa.Field(
        alias="Fault Level Replacement Cost ($M)"
    )
